version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: eitp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: eitp-grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning.yml:/etc/grafana/provisioning/datasources/provisioning.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=eitp_admin
      - GF_USERS_ALLOW_SIGN_UP=false

  alertmanager:
    image: prom/alertmanager:latest
    container_name: eitp-alertmanager
    ports:
      - "9093:9093"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: eitp-otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector/config.yaml

volumes:
  prometheus-data:
  grafana-data: