"""PLT 错误码枚举 - 全部以 EITP_PLT_ 前缀。"""

from __future__ import annotations

from enum import Enum


class PLTErrorCode(str, Enum):
    """EITP PLT 错误码枚举 - 全部以 EITP_PLT_ 前缀。"""

    AUDIT_UPDATE_FORBIDDEN = "EITP_PLT_AUDIT_UPDATE_FORBIDDEN"
    AUDIT_DELETE_FORBIDDEN = "EITP_PLT_AUDIT_DELETE_FORBIDDEN"
    AUDIT_TAMPER_DETECTED = "EITP_PLT_AUDIT_TAMPER_DETECTED"
    AUDIT_CROSS_TENANT_DENIED = "EITP_PLT_AUDIT_CROSS_TENANT_DENIED"
    AUDIT_NOT_FOUND = "EITP_PLT_AUDIT_NOT_FOUND"
    AUDIT_HASH_CHAIN_BROKEN = "EITP_PLT_AUDIT_HASH_CHAIN_BROKEN"
    AUDIT_RETENTION_INVALID = "EITP_PLT_AUDIT_RETENTION_INVALID"
    AUDIT_ARCHIVE_FAILED = "EITP_PLT_AUDIT_ARCHIVE_FAILED"
    AUDIT_EXPORT_DENIED = "EITP_PLT_AUDIT_EXPORT_DENIED"

    OUTBOX_DELIVERY_FAILED = "EITP_PLT_OUTBOX_DELIVERY_FAILED"
    OUTBOX_MAX_ATTEMPTS_EXCEEDED = "EITP_PLT_OUTBOX_MAX_ATTEMPTS_EXCEEDED"
    OUTBOX_EVENT_NOT_FOUND = "EITP_PLT_OUTBOX_EVENT_NOT_FOUND"
    OUTBOX_ALREADY_DELIVERED = "EITP_PLT_OUTBOX_ALREADY_DELIVERED"

    SAGA_COMPENSATION_FAILED = "EITP_PLT_SAGA_COMPENSATION_FAILED"
    SAGA_NOT_FOUND = "EITP_PLT_SAGA_NOT_FOUND"
    SAGA_STEP_FAILED = "EITP_PLT_SAGA_STEP_FAILED"
    SAGA_INVALID_TRANSITION = "EITP_PLT_SAGA_INVALID_TRANSITION"
    SAGA_MANUAL_INTERVENTION_REQUIRED = "EITP_PLT_SAGA_MANUAL_INTERVENTION_REQUIRED"

    IDEMPOTENCY_CONFLICT = "EITP_PLT_IDEMPOTENCY_CONFLICT"
    IDEMPOTENCY_KEY_FORMAT_VIOLATION = "EITP_PLT_IDEMPOTENCY_KEY_FORMAT_VIOLATION"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_PLT_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_EXPIRED = "EITP_PLT_IDEMPOTENCY_EXPIRED"

    PERMISSION_APPROVER_CONFLICT = "EITP_PLT_PERMISSION_APPROVER_CONFLICT"
    PERMISSION_MATRIX_CONFLICT = "EITP_PLT_PERMISSION_MATRIX_CONFLICT"
    PERMISSION_NOT_FOUND = "EITP_PLT_PERMISSION_NOT_FOUND"
    PERMISSION_APPROVAL_REJECTED = "EITP_PLT_PERMISSION_APPROVAL_REJECTED"
    PERMISSION_MENU_CYCLE = "EITP_PLT_PERMISSION_MENU_CYCLE"

    TENANT_QUOTA_EXCEEDED = "EITP_PLT_TENANT_QUOTA_EXCEEDED"
    TENANT_ARCHIVED = "EITP_PLT_TENANT_ARCHIVED"
    TENANT_FROZEN = "EITP_PLT_TENANT_FROZEN"
    TENANT_INIT_FAILED = "EITP_PLT_TENANT_INIT_FAILED"
    TENANT_INVALID_TRANSITION = "EITP_PLT_TENANT_INVALID_TRANSITION"
    TENANT_NOT_FOUND = "EITP_PLT_TENANT_NOT_FOUND"

    CONFIG_VALUE_INVALID = "EITP_PLT_CONFIG_VALUE_INVALID"
    CONFIG_NOT_FOUND = "EITP_PLT_CONFIG_NOT_FOUND"
    CONFIG_VERSION_CONFLICT = "EITP_PLT_CONFIG_VERSION_CONFLICT"
    CONFIG_DECRYPT_FAILED = "EITP_PLT_CONFIG_DECRYPT_FAILED"
    CONFIG_GRAY_RELEASE_INVALID = "EITP_PLT_CONFIG_GRAY_RELEASE_INVALID"

    RATE_LIMIT_EXCEEDED = "EITP_PLT_RATE_LIMIT_EXCEEDED"
    API_VERSION_DEPRECATED = "EITP_PLT_API_VERSION_DEPRECATED"
    API_VERSION_SUNSET = "EITP_PLT_API_VERSION_SUNSET"
    API_CONTRACT_NOT_FOUND = "EITP_PLT_API_CONTRACT_NOT_FOUND"

    JOB_TIMEOUT = "EITP_PLT_JOB_TIMEOUT"
    JOB_NOT_FOUND = "EITP_PLT_JOB_NOT_FOUND"
    JOB_CONFLICT = "EITP_PLT_JOB_CONFLICT"
    JOB_DISABLED = "EITP_PLT_JOB_DISABLED"
    JOB_HANDLER_NOT_FOUND = "EITP_PLT_JOB_HANDLER_NOT_FOUND"

    CERT_GATE_NOT_PASSED = "EITP_PLT_CERT_GATE_NOT_PASSED"
    PERFORMANCE_REGRESSION = "EITP_PLT_PERFORMANCE_REGRESSION"
    PERFORMANCE_BASELINE_NOT_FOUND = "EITP_PLT_PERFORMANCE_BASELINE_NOT_FOUND"

    ERRORCODE_DUPLICATE = "EITP_PLT_ERRORCODE_DUPLICATE"
    ERRORCODE_NOT_REGISTERED = "EITP_PLT_ERRORCODE_NOT_REGISTERED"

    DB_UNAVAILABLE = "EITP_PLT_DB_UNAVAILABLE"
    DB_RLS_VIOLATION = "EITP_PLT_DB_RLS_VIOLATION"
    UPSTREAM_TIMEOUT = "EITP_PLT_UPSTREAM_TIMEOUT"
    UPSTREAM_UNAVAILABLE = "EITP_PLT_UPSTREAM_UNAVAILABLE"

    ROLE_MIGRATION_CONFLICT = "EITP_PLT_ROLE_MIGRATION_CONFLICT"
    ROLE_PERMISSION_DENIED = "EITP_PLT_ROLE_PERMISSION_DENIED"

    OBSERVABILITY_METRIC_INVALID = "EITP_PLT_OBSERVABILITY_METRIC_INVALID"
    OBSERVABILITY_TRACE_NOT_FOUND = "EITP_PLT_OBSERVABILITY_TRACE_NOT_FOUND"

    CICD_PIPELINE_FAILED = "EITP_PLT_CICD_PIPELINE_FAILED"
    CICD_DEPLOY_ROLLBACK_FAILED = "EITP_PLT_CICD_DEPLOY_ROLLBACK_FAILED"

    HEALTH_CHECK_FAILED = "EITP_PLT_HEALTH_CHECK_FAILED"
    INTERNAL_ERROR = "EITP_PLT_INTERNAL_ERROR"