"""统一异常处理与错误码体系 - EITP_MT_* / EITP_IAM_* / EITP_INV_* / EITP_MDM_* / EITP_WMS_* 前缀并列共存。"""

from __future__ import annotations

from enum import Enum
from typing import Union

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from structlog import get_logger

logger = get_logger(__name__)


class ErrorCode(str, Enum):
    """EITP 错误码枚举 - 全部以 EITP_MT_ 前缀。"""

    # 租户上下文 (C-ISO-01)
    TENANT_CONTEXT_INVALID = "EITP_MT_TENANT_CONTEXT_INVALID"

    # 租户开通 (5.2.3)
    TENANT_ALREADY_EXISTS = "EITP_MT_TENANT_ALREADY_EXISTS"
    PROVISION_FAILED = "EITP_MT_PROVISION_FAILED"
    DEPROVISION_CONFIRM_REQUIRED = "EITP_MT_DEPROVISION_CONFIRM_REQUIRED"
    DEPROVISION_REQUIRES_DISABLE = "EITP_MT_DEPROVISION_REQUIRES_DISABLE"

    # 层级模型 (5.1.3)
    HIERARCHY_DEPTH_EXCEEDED = "EITP_MT_HIERARCHY_DEPTH_EXCEEDED"
    HIERARCHY_CROSS_TENANT = "EITP_MT_HIERARCHY_CROSS_TENANT"
    HIERARCHY_CIRCULAR_REF = "EITP_MT_HIERARCHY_CIRCULAR_REF"
    HIERARCHY_HAS_ACTIVE_DATA = "EITP_MT_HIERARCHY_HAS_ACTIVE_DATA"

    # 租户隔离 (5.3.3)
    CROSS_TENANT_REF_DENIED = "EITP_MT_CROSS_TENANT_REF_DENIED"

    # 配置 (5.4.3)
    CONFIG_INVALID = "EITP_MT_CONFIG_INVALID"
    CONFIG_INHERIT_CONFLICT = "EITP_MT_CONFIG_INHERIT_CONFLICT"
    FEATURE_HAS_ACTIVE_DATA = "EITP_MT_FEATURE_HAS_ACTIVE_DATA"

    # 业务规则 (5.5.3)
    WORKFLOW_INCOMPLETE = "EITP_MT_WORKFLOW_INCOMPLETE"

    # 集团模式 (5.6.3)
    GROUP_READONLY_VIOLATION = "EITP_MT_GROUP_READONLY_VIOLATION"
    GROUP_SNAPSHOT_DELAYED = "EITP_MT_GROUP_SNAPSHOT_DELAYED"
    MASTER_DATA_CONFLICT = "EITP_MT_MASTER_DATA_CONFLICT"
    MASTER_PROPAGATE_FAILED = "EITP_MT_MASTER_PROPAGATE_FAILED"
    SUBSIDIARY_ISOLATION_VIOLATION = "EITP_MT_SUBSIDIARY_ISOLATION_VIOLATION"

    # 主数据层级继承 (5.9.3)
    MASTER_BASE_READONLY = "EITP_MT_MASTER_BASE_READONLY"
    MASTER_ATTR_CONFLICT = "EITP_MT_MASTER_ATTR_CONFLICT"
    MASTER_NOT_FOUND = "EITP_MT_MASTER_NOT_FOUND"

    # 数据放置与迁移 (5.7.3)
    MIGRATION_IN_PROGRESS = "EITP_MT_MIGRATION_IN_PROGRESS"
    MIGRATION_VERIFY_FAILED = "EITP_MT_MIGRATION_VERIFY_FAILED"
    MIGRATION_TIMEOUT = "EITP_MT_MIGRATION_TIMEOUT"
    PLACEMENT_UNSUPPORTED = "EITP_MT_PLACEMENT_UNSUPPORTED"
    PLACEMENT_RESOURCE_INSUFFICIENT = "EITP_MT_PLACEMENT_RESOURCE_INSUFFICIENT"

    # 备份与恢复 (5.8.3)
    BACKUP_INTEGRITY_FAILED = "EITP_MT_BACKUP_INTEGRITY_FAILED"
    BACKUP_CORRUPTED = "EITP_MT_BACKUP_CORRUPTED"
    BACKUP_STORAGE_INSUFFICIENT = "EITP_MT_BACKUP_STORAGE_INSUFFICIENT"
    RESTORE_FAILED = "EITP_MT_RESTORE_FAILED"
    CROSS_TENANT_RESTORE_DENIED = "EITP_MT_CROSS_TENANT_RESTORE_DENIED"


class IAMErrorCode(str, Enum):
    """EITP IAM 错误码枚举 - 全部以 EITP_IAM_ 前缀。"""

    CREDENTIAL_INVALID = "EITP_IAM_CREDENTIAL_INVALID"
    ACCOUNT_LOCKED = "EITP_IAM_ACCOUNT_LOCKED"
    IP_BANNED = "EITP_IAM_IP_BANNED"
    TENANT_DISABLED = "EITP_IAM_TENANT_DISABLED"
    TENANT_MISMATCH = "EITP_IAM_TENANT_MISMATCH"
    TOKEN_EXPIRED = "EITP_IAM_TOKEN_EXPIRED"
    TOKEN_REVOKED = "EITP_IAM_TOKEN_REVOKED"
    TOKEN_SIGNATURE_INVALID = "EITP_IAM_TOKEN_SIGNATURE_INVALID"
    TOKEN_MISSING = "EITP_IAM_TOKEN_MISSING"
    REFRESH_TOKEN_REVOKED = "EITP_IAM_REFRESH_TOKEN_REVOKED"
    SESSION_EXPIRED = "EITP_IAM_SESSION_EXPIRED"
    PERMISSION_DENIED = "EITP_IAM_PERMISSION_DENIED"
    PERMISSION_MAPPING_MISSING = "EITP_IAM_PERMISSION_MAPPING_MISSING"
    PERMISSION_NOT_FOUND = "EITP_IAM_PERMISSION_NOT_FOUND"
    CROSS_TENANT_ROLE_DENIED = "EITP_IAM_CROSS_TENANT_ROLE_DENIED"
    CROSS_TENANT_REF_DENIED = "EITP_IAM_CROSS_TENANT_REF_DENIED"
    CROSS_TENANT_DATASCOPE_DENIED = "EITP_IAM_CROSS_TENANT_DATASCOPE_DENIED"
    CROSS_TENANT_AUDIT_DENIED = "EITP_IAM_CROSS_TENANT_AUDIT_DENIED"
    BUILTIN_ROLE_PROTECTED = "EITP_IAM_BUILTIN_ROLE_PROTECTED"
    ROLE_DUPLICATE = "EITP_IAM_ROLE_DUPLICATE"
    ROLE_HIERARCHY_VIOLATION = "EITP_IAM_ROLE_HIERARCHY_VIOLATION"
    TENANT_NOT_AUTHORIZED = "EITP_IAM_TENANT_NOT_AUTHORIZED"
    ENTERPRISE_SCOPE_EXCEEDED = "EITP_IAM_ENTERPRISE_SCOPE_EXCEEDED"
    USER_DUPLICATE = "EITP_IAM_USER_DUPLICATE"
    USER_NOT_FOUND = "EITP_IAM_USER_NOT_FOUND"
    OLD_PASSWORD_INVALID = "EITP_IAM_OLD_PASSWORD_INVALID"
    PASSWORD_WEAK = "EITP_IAM_PASSWORD_WEAK"
    PASSWORD_REUSE_DENIED = "EITP_IAM_PASSWORD_REUSE_DENIED"
    PASSWORD_POLICY_BELOW_PLATFORM = "EITP_IAM_PASSWORD_POLICY_BELOW_PLATFORM"
    DATASCOPE_UNRESOLVABLE = "EITP_IAM_DATASCOPE_UNRESOLVABLE"
    DEPT_HAS_ACTIVE_USERS = "EITP_IAM_DEPT_HAS_ACTIVE_USERS"
    DEACTIVATE_CONFIRM_REQUIRED = "EITP_IAM_DEACTIVATE_CONFIRM_REQUIRED"
    TENANT_CONTEXT_MISMATCH = "EITP_IAM_TENANT_CONTEXT_MISMATCH"
    TENANT_TOKEN_MISSING = "EITP_IAM_TENANT_TOKEN_MISSING"
    SERVICE_UNAVAILABLE = "EITP_IAM_SERVICE_UNAVAILABLE"


class INVErrorCode(str, Enum):
    """EITP INV 错误码枚举 - 全部以 EITP_INV_ 前缀。"""

    SKU_DUPLICATE = "EITP_INV_SKU_DUPLICATE"
    SKU_NOT_FOUND = "EITP_INV_SKU_NOT_FOUND"
    PRODUCT_DUPLICATE = "EITP_INV_PRODUCT_DUPLICATE"
    PRODUCT_NOT_FOUND = "EITP_INV_PRODUCT_NOT_FOUND"
    PRODUCT_HAS_ACTIVE_DOCUMENT = "EITP_INV_PRODUCT_HAS_ACTIVE_DOCUMENT"
    CATEGORY_DUPLICATE = "EITP_INV_CATEGORY_DUPLICATE"
    CROSS_TENANT_REF_DENIED = "EITP_INV_CROSS_TENANT_REF_DENIED"
    CROSS_TENANT_AUDIT_DENIED = "EITP_INV_CROSS_TENANT_AUDIT_DENIED"
    WAREHOUSE_DISABLED = "EITP_INV_WAREHOUSE_DISABLED"
    WAREHOUSE_NOT_FOUND = "EITP_INV_WAREHOUSE_NOT_FOUND"
    UNIT_CONVERSION_CONFLICT = "EITP_INV_UNIT_CONVERSION_CONFLICT"
    LOCATION_CAPACITY_EXCEEDED = "EITP_INV_LOCATION_CAPACITY_EXCEEDED"
    LOCATION_NOT_FOUND = "EITP_INV_LOCATION_NOT_FOUND"
    LEDGER_FIELD_REQUIRED = "EITP_INV_LEDGER_FIELD_REQUIRED"
    LEDGER_APPEND_FAILED = "EITP_INV_LEDGER_APPEND_FAILED"
    LEDGER_QUERY_RANGE_EXCEEDED = "EITP_INV_LEDGER_QUERY_RANGE_EXCEEDED"
    BALANCE_SNAPSHOT_INCONSISTENT = "EITP_INV_BALANCE_SNAPSHOT_INCONSISTENT"
    BALANCE_NOT_FOUND = "EITP_INV_BALANCE_NOT_FOUND"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_INV_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_CONFLICT = "EITP_INV_IDEMPOTENCY_KEY_CONFLICT"
    INSUFFICIENT_STOCK = "EITP_INV_INSUFFICIENT_STOCK"
    INSUFFICIENT_AVAILABLE = "EITP_INV_INSUFFICIENT_AVAILABLE"
    NEGATIVE_STOCK_FORCE_DENIED = "EITP_INV_NEGATIVE_STOCK_FORCE_DENIED"
    NEGATIVE_STOCK_APPROVAL_TIMEOUT = "EITP_INV_NEGATIVE_STOCK_APPROVAL_TIMEOUT"
    INVALID_STATE_TRANSITION = "EITP_INV_INVALID_STATE_TRANSITION"
    DOCUMENT_NOT_EDITABLE = "EITP_INV_DOCUMENT_NOT_EDITABLE"
    DOCUMENT_NOT_DELETABLE = "EITP_INV_DOCUMENT_NOT_DELETABLE"
    DOCUMENT_NOT_FOUND = "EITP_INV_DOCUMENT_NOT_FOUND"
    STATE_TRANSITION_DENIED = "EITP_INV_STATE_TRANSITION_DENIED"
    OWNERSHIP_REQUIRED = "EITP_INV_OWNERSHIP_REQUIRED"
    COST_MODEL_NOT_CONFIGURED = "EITP_INV_COST_MODEL_NOT_CONFIGURED"
    COST_MODEL_SWITCH_CONFLICT = "EITP_INV_COST_MODEL_SWITCH_CONFLICT"
    STOCK_BLOCKED_BY_COUNT = "EITP_INV_STOCK_BLOCKED_BY_COUNT"
    COUNT_DIFF_EXCEEDED_THRESHOLD = "EITP_INV_COUNT_DIFF_EXCEEDED_THRESHOLD"
    ADJUST_EXCEED_ONHAND = "EITP_INV_ADJUST_EXCEED_ONHAND"
    BLOCK_EXCEED_ONHAND = "EITP_INV_BLOCK_EXCEED_ONHAND"
    BATCH_SIZE_EXCEEDED = "EITP_INV_BATCH_SIZE_EXCEEDED"
    RESERVATION_NOT_FOUND = "EITP_INV_RESERVATION_NOT_FOUND"
    RESERVATION_ALREADY_RELEASED = "EITP_INV_RESERVATION_ALREADY_RELEASED"
    RESERVATION_EXPIRED = "EITP_INV_RESERVATION_EXPIRED"


class MDMErrorCode(str, Enum):
    """EITP MDM 错误码枚举 - 全部以 EITP_MDM_ 前缀。"""

    GROUP_SKU_DUPLICATE = "EITP_MDM_GROUP_SKU_DUPLICATE"
    GROUP_PRODUCT_NOT_PUBLISHED = "EITP_MDM_GROUP_PRODUCT_NOT_PUBLISHED"
    GROUP_PRODUCT_DISABLED = "EITP_MDM_GROUP_PRODUCT_DISABLED"
    CROSS_ENTERPRISE_REF_DENIED = "EITP_MDM_CROSS_ENTERPRISE_REF_DENIED"
    GROUP_BASE_ATTRIBUTE_READONLY = "EITP_MDM_GROUP_BASE_ATTRIBUTE_READONLY"
    DUPLICATE_REFERENCE = "EITP_MDM_DUPLICATE_REFERENCE"
    SPEC_INSTANCE_INVALID = "EITP_MDM_SPEC_INSTANCE_INVALID"
    ATTRIBUTE_INSTANCE_INVALID = "EITP_MDM_ATTRIBUTE_INSTANCE_INVALID"
    SPEC_TEMPLATE_CYCLE = "EITP_MDM_SPEC_TEMPLATE_CYCLE"
    BARCODE_DUPLICATE = "EITP_MDM_BARCODE_DUPLICATE"
    CATEGORY_CYCLE = "EITP_MDM_CATEGORY_CYCLE"
    CATEGORY_MULTI_BELONG_DENIED = "EITP_MDM_CATEGORY_MULTI_BELONG_DENIED"
    GROUP_CATEGORY_PERMISSION_DENIED = "EITP_MDM_GROUP_CATEGORY_PERMISSION_DENIED"
    UNIT_CONVERSION_CONFLICT = "EITP_MDM_UNIT_CONVERSION_CONFLICT"
    GROUP_UNIT_PERMISSION_DENIED = "EITP_MDM_GROUP_UNIT_PERMISSION_DENIED"
    INVALID_GOVERNANCE_STATE_TRANSITION = "EITP_MDM_INVALID_GOVERNANCE_STATE_TRANSITION"
    GOVERNANCE_REQUEST_NOT_EDITABLE = "EITP_MDM_GOVERNANCE_REQUEST_NOT_EDITABLE"
    GOVERNANCE_APPROVAL_DENIED = "EITP_MDM_GOVERNANCE_APPROVAL_DENIED"
    CROSS_LEVEL_GOVERNANCE_DENIED = "EITP_MDM_CROSS_LEVEL_GOVERNANCE_DENIED"
    VERSION_NOT_FOUND = "EITP_MDM_VERSION_NOT_FOUND"
    GROUP_PRODUCT_HAS_ACTIVE_REFERENCE = "EITP_MDM_GROUP_PRODUCT_HAS_ACTIVE_REFERENCE"
    REFERENCE_HAS_ACTIVE_DOCUMENT = "EITP_MDM_REFERENCE_HAS_ACTIVE_DOCUMENT"
    NEGATIVE_POLICY_PERMISSION_DENIED = "EITP_MDM_NEGATIVE_POLICY_PERMISSION_DENIED"
    CROSS_TENANT_POLICY_DENIED = "EITP_MDM_CROSS_TENANT_POLICY_DENIED"
    NEGATIVE_POLICY_REASON_REQUIRED = "EITP_MDM_NEGATIVE_POLICY_REASON_REQUIRED"
    NEGATIVE_POLICY_DEFAULT_MUST_STRICT = "EITP_MDM_NEGATIVE_POLICY_DEFAULT_MUST_STRICT"
    LEDGER_TRIGGER_GUARD_FAILED = "EITP_MDM_LEDGER_TRIGGER_GUARD_FAILED"
    IDEMPOTENCY_FAIL_SAFE_VIOLATION = "EITP_MDM_IDEMPOTENCY_FAIL_SAFE_VIOLATION"
    INV_REGRESSION_FAILED = "EITP_MDM_INV_REGRESSION_FAILED"
    PRODUCT_NOT_AVAILABLE = "EITP_MDM_PRODUCT_NOT_AVAILABLE"
    SERVICE_UNAVAILABLE = "EITP_MDM_SERVICE_UNAVAILABLE"
    DIRECT_ACCESS_DENIED = "EITP_MDM_DIRECT_ACCESS_DENIED"
    GROUP_CATALOG_PERMISSION_DENIED = "EITP_MDM_GROUP_CATALOG_PERMISSION_DENIED"


class WMSErrorCode(str, Enum):
    """EITP WMS 错误码枚举 - 全部以 EITP_WMS_ 前缀。"""

    LOCATION_CODE_DUPLICATE = "EITP_WMS_LOCATION_CODE_DUPLICATE"
    LOCATION_CAPACITY_EXCEEDED = "EITP_WMS_LOCATION_CAPACITY_EXCEEDED"
    LOCATION_DISABLED = "EITP_WMS_LOCATION_DISABLED"
    LOCATION_NOT_FOUND = "EITP_WMS_LOCATION_NOT_FOUND"
    ZONE_FUNCTION_MISMATCH = "EITP_WMS_ZONE_FUNCTION_MISMATCH"
    ZONE_NOT_FOUND = "EITP_WMS_ZONE_NOT_FOUND"
    AREA_NOT_FOUND = "EITP_WMS_AREA_NOT_FOUND"
    HIERARCHY_CYCLE = "EITP_WMS_HIERARCHY_CYCLE"
    DIRECT_POSITION_MODIFY_DENIED = "EITP_WMS_DIRECT_POSITION_MODIFY_DENIED"
    INV_INCONSISTENT = "EITP_WMS_INV_INCONSISTENT"
    RECEIVING_OVER_RECEIVED = "EITP_WMS_RECEIVING_OVER_RECEIVED"
    RECEIVING_ZONE_INVALID = "EITP_WMS_RECEIVING_ZONE_INVALID"
    RECEIVING_NOT_FOUND = "EITP_WMS_RECEIVING_NOT_FOUND"
    RECEIVING_ALREADY_COMPLETED = "EITP_WMS_RECEIVING_ALREADY_COMPLETED"
    PUTAWAY_CAPACITY_EXCEEDED = "EITP_WMS_PUTAWAY_CAPACITY_EXCEEDED"
    PUTAWAY_LOCATION_DISABLED = "EITP_WMS_PUTAWAY_LOCATION_DISABLED"
    PUTAWAY_ZONE_NOT_STORAGE = "EITP_WMS_PUTAWAY_ZONE_NOT_STORAGE"
    PUTAWAY_NOT_FOUND = "EITP_WMS_PUTAWAY_NOT_FOUND"
    PUTAWAY_ALREADY_COMPLETED = "EITP_WMS_PUTAWAY_ALREADY_COMPLETED"
    PICKING_INSUFFICIENT_AVAILABLE = "EITP_WMS_PICKING_INSUFFICIENT_AVAILABLE"
    PICKING_STATUS_UNAVAILABLE = "EITP_WMS_PICKING_STATUS_UNAVAILABLE"
    PICKING_QTY_MISMATCH = "EITP_WMS_PICKING_QTY_MISMATCH"
    PICKING_NOT_FOUND = "EITP_WMS_PICKING_NOT_FOUND"
    PICKING_ALREADY_COMPLETED = "EITP_WMS_PICKING_ALREADY_COMPLETED"
    TRANSFER_CROSS_WAREHOUSE = "EITP_WMS_TRANSFER_CROSS_WAREHOUSE"
    TRANSFER_INSUFFICIENT_SOURCE = "EITP_WMS_TRANSFER_INSUFFICIENT_SOURCE"
    TRANSFER_TARGET_CAPACITY_EXCEEDED = "EITP_WMS_TRANSFER_TARGET_CAPACITY_EXCEEDED"
    TRANSFER_NOT_FOUND = "EITP_WMS_TRANSFER_NOT_FOUND"
    SHIPPING_PICKING_NOT_COMPLETED = "EITP_WMS_SHIPPING_PICKING_NOT_COMPLETED"
    SHIPPING_ZONE_INVALID = "EITP_WMS_SHIPPING_ZONE_INVALID"
    SHIPPING_NOT_FOUND = "EITP_WMS_SHIPPING_NOT_FOUND"
    SHIPPING_ALREADY_COMPLETED = "EITP_WMS_SHIPPING_ALREADY_COMPLETED"
    TASK_INVALID_STATE_TRANSITION = "EITP_WMS_TASK_INVALID_STATE_TRANSITION"
    TASK_ASSIGNMENT_DENIED = "EITP_WMS_TASK_ASSIGNMENT_DENIED"
    TASK_NOT_FOUND = "EITP_WMS_TASK_NOT_FOUND"
    TASK_ALREADY_COMPLETED = "EITP_WMS_TASK_ALREADY_COMPLETED"
    DIRECT_INVENTORY_MODIFY_DENIED = "EITP_WMS_DIRECT_INVENTORY_MODIFY_DENIED"
    INV_TRANSACTION_FAILED = "EITP_WMS_INV_TRANSACTION_FAILED"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_WMS_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_CONFLICT = "EITP_WMS_IDEMPOTENCY_KEY_CONFLICT"
    SKU_NOT_FOUND = "EITP_WMS_SKU_NOT_FOUND"
    WAREHOUSE_NOT_FOUND = "EITP_WMS_WAREHOUSE_NOT_FOUND"
    WAREHOUSE_DISABLED = "EITP_WMS_WAREHOUSE_DISABLED"
    CROSS_TENANT_REF_DENIED = "EITP_WMS_CROSS_TENANT_REF_DENIED"
    OWNERSHIP_REQUIRED = "EITP_WMS_OWNERSHIP_REQUIRED"
    BATCH_REQUIRED = "EITP_WMS_BATCH_REQUIRED"
    EXPIRY_WARNING = "EITP_WMS_EXPIRY_WARNING"
    SERVICE_UNAVAILABLE = "EITP_WMS_SERVICE_UNAVAILABLE"


class PURErrorCode(str, Enum):
    """EITP PUR 错误码枚举 - 全部以 EITP_PUR_ 前缀。"""

    SUPPLIER_CODE_DUPLICATE = "EITP_PUR_SUPPLIER_CODE_DUPLICATE"
    SUPPLIER_NOT_ACTIVE = "EITP_PUR_SUPPLIER_NOT_ACTIVE"
    SUPPLIER_DISABLED = "EITP_PUR_SUPPLIER_DISABLED"
    SUPPLIER_SCOPE_MISMATCH = "EITP_PUR_SUPPLIER_SCOPE_MISMATCH"
    SUPPLIER_NOT_FOUND = "EITP_PUR_SUPPLIER_NOT_FOUND"
    CROSS_TENANT_SUPPLIER_DENIED = "EITP_PUR_CROSS_TENANT_SUPPLIER_DENIED"
    REQUEST_BUDGET_EXCEEDED = "EITP_PUR_REQUEST_BUDGET_EXCEEDED"
    REQUEST_NOT_APPROVED = "EITP_PUR_REQUEST_NOT_APPROVED"
    REQUEST_NOT_FOUND = "EITP_PUR_REQUEST_NOT_FOUND"
    SKU_DISABLED = "EITP_PUR_SKU_DISABLED"
    SKU_NOT_FOUND = "EITP_PUR_SKU_NOT_FOUND"
    ORDER_INVALID_STATE_TRANSITION = "EITP_PUR_ORDER_INVALID_STATE_TRANSITION"
    ORDER_NOT_APPROVED = "EITP_PUR_ORDER_NOT_APPROVED"
    ORDER_CANCEL_WITH_RECEIVED = "EITP_PUR_ORDER_CANCEL_WITH_RECEIVED"
    ORDER_NOT_FOUND = "EITP_PUR_ORDER_NOT_FOUND"
    ORDER_LINE_NOT_FOUND = "EITP_PUR_ORDER_LINE_NOT_FOUND"
    RECEIPT_OVER_RECEIVED = "EITP_PUR_RECEIPT_OVER_RECEIVED"
    RECEIPT_ORDER_INVALID = "EITP_PUR_RECEIPT_ORDER_INVALID"
    RECEIPT_NOT_FOUND = "EITP_PUR_RECEIPT_NOT_FOUND"
    WMS_RECEIVING_FAILED = "EITP_PUR_WMS_RECEIVING_FAILED"
    DIRECT_INVENTORY_MODIFY_DENIED = "EITP_PUR_DIRECT_INVENTORY_MODIFY_DENIED"
    RETURN_OVER_RETURNED = "EITP_PUR_RETURN_OVER_RETURNED"
    RETURN_INVENTORY_FAILED = "EITP_PUR_RETURN_INVENTORY_FAILED"
    RETURN_NOT_APPROVED = "EITP_PUR_RETURN_NOT_APPROVED"
    RETURN_NOT_FOUND = "EITP_PUR_RETURN_NOT_FOUND"
    SETTLEMENT_RECONCILE_DIFF_EXCEEDED = "EITP_PUR_SETTLEMENT_RECONCILE_DIFF_EXCEEDED"
    SETTLEMENT_NOT_FOUND = "EITP_PUR_SETTLEMENT_NOT_FOUND"
    INVOICE_MATCH_DIFF_EXCEEDED = "EITP_PUR_INVOICE_MATCH_DIFF_EXCEEDED"
    INVOICE_NOT_FOUND = "EITP_PUR_INVOICE_NOT_FOUND"
    FINANCIAL_API_FAILED = "EITP_PUR_FINANCIAL_API_FAILED"
    DIRECT_COST_MODIFY_DENIED = "EITP_PUR_DIRECT_COST_MODIFY_DENIED"
    WMS_INV_INCONSISTENT = "EITP_PUR_WMS_INV_INCONSISTENT"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_PUR_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_CONFLICT = "EITP_PUR_IDEMPOTENCY_KEY_CONFLICT"
    CROSS_TENANT_REF_DENIED = "EITP_PUR_CROSS_TENANT_REF_DENIED"
    OWNERSHIP_REQUIRED = "EITP_PUR_OWNERSHIP_REQUIRED"
    BUDGET_NOT_FOUND = "EITP_PUR_BUDGET_NOT_FOUND"
    APPROVAL_TIMEOUT = "EITP_PUR_APPROVAL_TIMEOUT"
    PAYMENT_NOT_FOUND = "EITP_PUR_PAYMENT_NOT_FOUND"
    PAYMENT_ALREADY_COMPLETED = "EITP_PUR_PAYMENT_ALREADY_COMPLETED"
    ASN_NOT_FOUND = "EITP_PUR_ASN_NOT_FOUND"
    QUOTATION_NOT_FOUND = "EITP_PUR_QUOTATION_NOT_FOUND"
    EVALUATION_NOT_FOUND = "EITP_PUR_EVALUATION_NOT_FOUND"
    RMQ_INVALID_STATE_TRANSITION = "EITP_PUR_RMQ_INVALID_STATE_TRANSITION"
    FRAMEWORK_AGREEMENT_EXPIRED = "EITP_PUR_FRAMEWORK_AGREEMENT_EXPIRED"
    FRAMEWORK_AGREEMENT_QTY_EXCEEDED = "EITP_PUR_FRAMEWORK_AGREEMENT_QTY_EXCEEDED"
    PORTAL_PERMISSION_DENIED = "EITP_PUR_PORTAL_PERMISSION_DENIED"
    SERVICE_UNAVAILABLE = "EITP_PUR_SERVICE_UNAVAILABLE"


AnyErrorCode = Union[ErrorCode, IAMErrorCode, INVErrorCode, MDMErrorCode, WMSErrorCode, PURErrorCode]


class DomainError(Exception):
    """领域错误基类。"""

    def __init__(self, code: AnyErrorCode, message: str, details: dict | None = None) -> None:
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(message)


class IAMError(DomainError):
    """IAM 领域错误。"""
    pass


class INVError(DomainError):
    """INV 领域错误。"""
    pass


class MDMError(DomainError):
    """MDM 领域错误。"""
    pass


class WMSError(DomainError):
    """WMS 领域错误。"""
    pass


class PURError(DomainError):
    """PUR 领域错误。"""
    pass


class TenantContextError(DomainError):
    def __init__(self, message: str = "租户上下文无效或缺失") -> None:
        super().__init__(ErrorCode.TENANT_CONTEXT_INVALID, message)


class HierarchyError(DomainError):
    pass


class ConfigError(DomainError):
    pass


class GroupError(DomainError):
    pass


def setup_exception_handlers(app: FastAPI) -> None:
    """注册全局异常处理器。"""

    @app.exception_handler(DomainError)
    async def domain_error_handler(request: Request, exc: DomainError) -> JSONResponse:
        logger.warning(
            "domain_error",
            error_code=exc.code.value,
            message=exc.message,
            path=request.url.path,
            trace_id=getattr(request.state, "trace_id", None),
        )
        status = _status_for_code(exc.code)
        return JSONResponse(
            status_code=status,
            content={
                "error_code": exc.code.value,
                "message": exc.message,
                "details": exc.details,
            },
        )

    @app.exception_handler(Exception)
    async def unhandled_error_handler(request: Request, exc: Exception) -> JSONResponse:
        logger.exception(
            "unhandled_error",
            path=request.url.path,
            trace_id=getattr(request.state, "trace_id", None),
        )
        return JSONResponse(
            status_code=500,
            content={
                "error_code": "EITP_MT_INTERNAL_ERROR",
                "message": "内部服务器错误",
            },
        )


def _status_for_code(code: AnyErrorCode) -> int:
    if isinstance(code, PURErrorCode):
        return _status_for_pur_code(code)
    if isinstance(code, WMSErrorCode):
        return _status_for_wms_code(code)
    if isinstance(code, MDMErrorCode):
        return _status_for_mdm_code(code)
    if isinstance(code, INVErrorCode):
        return _status_for_inv_code(code)
    if isinstance(code, IAMErrorCode):
        return _status_for_iam_code(code)
    if code in {ErrorCode.TENANT_CONTEXT_INVALID, ErrorCode.CROSS_TENANT_REF_DENIED}:
        return 401 if code == ErrorCode.TENANT_CONTEXT_INVALID else 403
    if code == ErrorCode.TENANT_ALREADY_EXISTS:
        return 409
    if code in {
        ErrorCode.HIERARCHY_DEPTH_EXCEEDED,
        ErrorCode.HIERARCHY_CROSS_TENANT,
        ErrorCode.HIERARCHY_CIRCULAR_REF,
        ErrorCode.HIERARCHY_HAS_ACTIVE_DATA,
        ErrorCode.CONFIG_INVALID,
        ErrorCode.CONFIG_INHERIT_CONFLICT,
        ErrorCode.FEATURE_HAS_ACTIVE_DATA,
        ErrorCode.WORKFLOW_INCOMPLETE,
        ErrorCode.DEPROVISION_REQUIRES_DISABLE,
        ErrorCode.MASTER_DATA_CONFLICT,
        ErrorCode.MASTER_PROPAGATE_FAILED,
        ErrorCode.SUBSIDIARY_ISOLATION_VIOLATION,
        ErrorCode.MASTER_BASE_READONLY,
        ErrorCode.MASTER_ATTR_CONFLICT,
        ErrorCode.MASTER_NOT_FOUND,
        ErrorCode.MIGRATION_VERIFY_FAILED,
        ErrorCode.MIGRATION_TIMEOUT,
        ErrorCode.PLACEMENT_RESOURCE_INSUFFICIENT,
    }:
        return 422
    if code == ErrorCode.DEPROVISION_CONFIRM_REQUIRED:
        return 400
    if code == ErrorCode.GROUP_READONLY_VIOLATION:
        return 403
    if code == ErrorCode.CROSS_TENANT_RESTORE_DENIED:
        return 403
    if code == ErrorCode.GROUP_SNAPSHOT_DELAYED:
        return 200
    return 400


def _status_for_iam_code(code: IAMErrorCode) -> int:
    _401_CODES = {
        IAMErrorCode.CREDENTIAL_INVALID,
        IAMErrorCode.TOKEN_EXPIRED,
        IAMErrorCode.TOKEN_REVOKED,
        IAMErrorCode.TOKEN_SIGNATURE_INVALID,
        IAMErrorCode.TOKEN_MISSING,
        IAMErrorCode.REFRESH_TOKEN_REVOKED,
        IAMErrorCode.SESSION_EXPIRED,
        IAMErrorCode.TENANT_TOKEN_MISSING,
    }
    _403_CODES = {
        IAMErrorCode.ACCOUNT_LOCKED,
        IAMErrorCode.IP_BANNED,
        IAMErrorCode.TENANT_DISABLED,
        IAMErrorCode.TENANT_MISMATCH,
        IAMErrorCode.PERMISSION_DENIED,
        IAMErrorCode.CROSS_TENANT_ROLE_DENIED,
        IAMErrorCode.CROSS_TENANT_REF_DENIED,
        IAMErrorCode.CROSS_TENANT_DATASCOPE_DENIED,
        IAMErrorCode.CROSS_TENANT_AUDIT_DENIED,
        IAMErrorCode.BUILTIN_ROLE_PROTECTED,
        IAMErrorCode.ROLE_HIERARCHY_VIOLATION,
        IAMErrorCode.TENANT_NOT_AUTHORIZED,
        IAMErrorCode.ENTERPRISE_SCOPE_EXCEEDED,
        IAMErrorCode.TENANT_CONTEXT_MISMATCH,
    }
    _409_CODES = {
        IAMErrorCode.USER_DUPLICATE,
        IAMErrorCode.ROLE_DUPLICATE,
    }
    _422_CODES = {
        IAMErrorCode.PASSWORD_WEAK,
        IAMErrorCode.PASSWORD_REUSE_DENIED,
        IAMErrorCode.PASSWORD_POLICY_BELOW_PLATFORM,
        IAMErrorCode.OLD_PASSWORD_INVALID,
        IAMErrorCode.DATASCOPE_UNRESOLVABLE,
        IAMErrorCode.PERMISSION_MAPPING_MISSING,
    }
    _400_CODES = {
        IAMErrorCode.PERMISSION_NOT_FOUND,
        IAMErrorCode.USER_NOT_FOUND,
        IAMErrorCode.DEPT_HAS_ACTIVE_USERS,
        IAMErrorCode.DEACTIVATE_CONFIRM_REQUIRED,
        IAMErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _401_CODES:
        return 401
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _400_CODES:
        return 400
    return 400


def _status_for_inv_code(code: INVErrorCode) -> int:
    _404_CODES = {
        INVErrorCode.SKU_NOT_FOUND,
        INVErrorCode.PRODUCT_NOT_FOUND,
        INVErrorCode.WAREHOUSE_NOT_FOUND,
        INVErrorCode.LOCATION_NOT_FOUND,
        INVErrorCode.BALANCE_NOT_FOUND,
        INVErrorCode.DOCUMENT_NOT_FOUND,
        INVErrorCode.RESERVATION_NOT_FOUND,
    }
    _403_CODES = {
        INVErrorCode.CROSS_TENANT_REF_DENIED,
        INVErrorCode.CROSS_TENANT_AUDIT_DENIED,
        INVErrorCode.NEGATIVE_STOCK_FORCE_DENIED,
        INVErrorCode.STATE_TRANSITION_DENIED,
        INVErrorCode.STOCK_BLOCKED_BY_COUNT,
        INVErrorCode.DOCUMENT_NOT_EDITABLE,
        INVErrorCode.DOCUMENT_NOT_DELETABLE,
    }
    _409_CODES = {
        INVErrorCode.SKU_DUPLICATE,
        INVErrorCode.PRODUCT_DUPLICATE,
        INVErrorCode.CATEGORY_DUPLICATE,
        INVErrorCode.IDEMPOTENCY_KEY_CONFLICT,
        INVErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        INVErrorCode.UNIT_CONVERSION_CONFLICT,
        INVErrorCode.COST_MODEL_SWITCH_CONFLICT,
        INVErrorCode.RESERVATION_ALREADY_RELEASED,
    }
    _422_CODES = {
        INVErrorCode.PRODUCT_HAS_ACTIVE_DOCUMENT,
        INVErrorCode.WAREHOUSE_DISABLED,
        INVErrorCode.LOCATION_CAPACITY_EXCEEDED,
        INVErrorCode.LEDGER_FIELD_REQUIRED,
        INVErrorCode.LEDGER_APPEND_FAILED,
        INVErrorCode.LEDGER_QUERY_RANGE_EXCEEDED,
        INVErrorCode.BALANCE_SNAPSHOT_INCONSISTENT,
        INVErrorCode.INSUFFICIENT_STOCK,
        INVErrorCode.INSUFFICIENT_AVAILABLE,
        INVErrorCode.INVALID_STATE_TRANSITION,
        INVErrorCode.OWNERSHIP_REQUIRED,
        INVErrorCode.COST_MODEL_NOT_CONFIGURED,
        INVErrorCode.COUNT_DIFF_EXCEEDED_THRESHOLD,
        INVErrorCode.ADJUST_EXCEED_ONHAND,
        INVErrorCode.BLOCK_EXCEED_ONHAND,
        INVErrorCode.BATCH_SIZE_EXCEEDED,
        INVErrorCode.RESERVATION_EXPIRED,
    }
    _408_CODES = {
        INVErrorCode.NEGATIVE_STOCK_APPROVAL_TIMEOUT,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _408_CODES:
        return 408
    return 400


def _status_for_mdm_code(code: MDMErrorCode) -> int:
    _404_CODES = {
        MDMErrorCode.VERSION_NOT_FOUND,
        MDMErrorCode.GROUP_PRODUCT_NOT_PUBLISHED,
    }
    _403_CODES = {
        MDMErrorCode.CROSS_ENTERPRISE_REF_DENIED,
        MDMErrorCode.GROUP_BASE_ATTRIBUTE_READONLY,
        MDMErrorCode.CATEGORY_MULTI_BELONG_DENIED,
        MDMErrorCode.GROUP_CATEGORY_PERMISSION_DENIED,
        MDMErrorCode.GROUP_UNIT_PERMISSION_DENIED,
        MDMErrorCode.GOVERNANCE_APPROVAL_DENIED,
        MDMErrorCode.CROSS_LEVEL_GOVERNANCE_DENIED,
        MDMErrorCode.GROUP_PRODUCT_HAS_ACTIVE_REFERENCE,
        MDMErrorCode.REFERENCE_HAS_ACTIVE_DOCUMENT,
        MDMErrorCode.NEGATIVE_POLICY_PERMISSION_DENIED,
        MDMErrorCode.CROSS_TENANT_POLICY_DENIED,
        MDMErrorCode.NEGATIVE_POLICY_DEFAULT_MUST_STRICT,
        MDMErrorCode.LEDGER_TRIGGER_GUARD_FAILED,
        MDMErrorCode.IDEMPOTENCY_FAIL_SAFE_VIOLATION,
        MDMErrorCode.INV_REGRESSION_FAILED,
        MDMErrorCode.PRODUCT_NOT_AVAILABLE,
        MDMErrorCode.DIRECT_ACCESS_DENIED,
        MDMErrorCode.GROUP_CATALOG_PERMISSION_DENIED,
        MDMErrorCode.GROUP_PRODUCT_DISABLED,
    }
    _409_CODES = {
        MDMErrorCode.GROUP_SKU_DUPLICATE,
        MDMErrorCode.DUPLICATE_REFERENCE,
        MDMErrorCode.BARCODE_DUPLICATE,
    }
    _422_CODES = {
        MDMErrorCode.SPEC_INSTANCE_INVALID,
        MDMErrorCode.ATTRIBUTE_INSTANCE_INVALID,
        MDMErrorCode.SPEC_TEMPLATE_CYCLE,
        MDMErrorCode.CATEGORY_CYCLE,
        MDMErrorCode.UNIT_CONVERSION_CONFLICT,
        MDMErrorCode.INVALID_GOVERNANCE_STATE_TRANSITION,
        MDMErrorCode.GOVERNANCE_REQUEST_NOT_EDITABLE,
        MDMErrorCode.NEGATIVE_POLICY_REASON_REQUIRED,
    }
    _500_CODES = {
        MDMErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    return 400


def _status_for_wms_code(code: WMSErrorCode) -> int:
    _404_CODES = {
        WMSErrorCode.LOCATION_NOT_FOUND,
        WMSErrorCode.ZONE_NOT_FOUND,
        WMSErrorCode.AREA_NOT_FOUND,
        WMSErrorCode.RECEIVING_NOT_FOUND,
        WMSErrorCode.PUTAWAY_NOT_FOUND,
        WMSErrorCode.PICKING_NOT_FOUND,
        WMSErrorCode.TRANSFER_NOT_FOUND,
        WMSErrorCode.SHIPPING_NOT_FOUND,
        WMSErrorCode.TASK_NOT_FOUND,
        WMSErrorCode.SKU_NOT_FOUND,
        WMSErrorCode.WAREHOUSE_NOT_FOUND,
    }
    _403_CODES = {
        WMSErrorCode.LOCATION_DISABLED,
        WMSErrorCode.DIRECT_POSITION_MODIFY_DENIED,
        WMSErrorCode.PUTAWAY_LOCATION_DISABLED,
        WMSErrorCode.PICKING_STATUS_UNAVAILABLE,
        WMSErrorCode.SHIPPING_PICKING_NOT_COMPLETED,
        WMSErrorCode.TASK_ASSIGNMENT_DENIED,
        WMSErrorCode.DIRECT_INVENTORY_MODIFY_DENIED,
        WMSErrorCode.CROSS_TENANT_REF_DENIED,
        WMSErrorCode.WAREHOUSE_DISABLED,
        WMSErrorCode.OWNERSHIP_REQUIRED,
    }
    _409_CODES = {
        WMSErrorCode.LOCATION_CODE_DUPLICATE,
        WMSErrorCode.IDEMPOTENCY_KEY_CONFLICT,
        WMSErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        WMSErrorCode.RECEIVING_ALREADY_COMPLETED,
        WMSErrorCode.PUTAWAY_ALREADY_COMPLETED,
        WMSErrorCode.PICKING_ALREADY_COMPLETED,
        WMSErrorCode.SHIPPING_ALREADY_COMPLETED,
        WMSErrorCode.TASK_ALREADY_COMPLETED,
    }
    _422_CODES = {
        WMSErrorCode.LOCATION_CAPACITY_EXCEEDED,
        WMSErrorCode.ZONE_FUNCTION_MISMATCH,
        WMSErrorCode.HIERARCHY_CYCLE,
        WMSErrorCode.INV_INCONSISTENT,
        WMSErrorCode.RECEIVING_OVER_RECEIVED,
        WMSErrorCode.RECEIVING_ZONE_INVALID,
        WMSErrorCode.PUTAWAY_CAPACITY_EXCEEDED,
        WMSErrorCode.PUTAWAY_ZONE_NOT_STORAGE,
        WMSErrorCode.PICKING_INSUFFICIENT_AVAILABLE,
        WMSErrorCode.PICKING_QTY_MISMATCH,
        WMSErrorCode.TRANSFER_CROSS_WAREHOUSE,
        WMSErrorCode.TRANSFER_INSUFFICIENT_SOURCE,
        WMSErrorCode.TRANSFER_TARGET_CAPACITY_EXCEEDED,
        WMSErrorCode.SHIPPING_ZONE_INVALID,
        WMSErrorCode.TASK_INVALID_STATE_TRANSITION,
        WMSErrorCode.INV_TRANSACTION_FAILED,
        WMSErrorCode.BATCH_REQUIRED,
    }
    _500_CODES = {
        WMSErrorCode.SERVICE_UNAVAILABLE,
    }
    _200_CODES = {
        WMSErrorCode.EXPIRY_WARNING,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    if code in _200_CODES:
        return 200
    return 400


def _status_for_pur_code(code: PURErrorCode) -> int:
    _404_CODES = {
        PURErrorCode.SUPPLIER_NOT_FOUND,
        PURErrorCode.REQUEST_NOT_FOUND,
        PURErrorCode.ORDER_NOT_FOUND,
        PURErrorCode.ORDER_LINE_NOT_FOUND,
        PURErrorCode.RECEIPT_NOT_FOUND,
        PURErrorCode.RETURN_NOT_FOUND,
        PURErrorCode.SETTLEMENT_NOT_FOUND,
        PURErrorCode.INVOICE_NOT_FOUND,
        PURErrorCode.PAYMENT_NOT_FOUND,
        PURErrorCode.ASN_NOT_FOUND,
        PURErrorCode.QUOTATION_NOT_FOUND,
        PURErrorCode.EVALUATION_NOT_FOUND,
        PURErrorCode.SKU_NOT_FOUND,
        PURErrorCode.BUDGET_NOT_FOUND,
    }
    _403_CODES = {
        PURErrorCode.SUPPLIER_DISABLED,
        PURErrorCode.SUPPLIER_NOT_ACTIVE,
        PURErrorCode.CROSS_TENANT_SUPPLIER_DENIED,
        PURErrorCode.CROSS_TENANT_REF_DENIED,
        PURErrorCode.DIRECT_INVENTORY_MODIFY_DENIED,
        PURErrorCode.DIRECT_COST_MODIFY_DENIED,
        PURErrorCode.REQUEST_NOT_APPROVED,
        PURErrorCode.ORDER_NOT_APPROVED,
        PURErrorCode.RETURN_NOT_APPROVED,
        PURErrorCode.OWNERSHIP_REQUIRED,
        PURErrorCode.PORTAL_PERMISSION_DENIED,
    }
    _409_CODES = {
        PURErrorCode.SUPPLIER_CODE_DUPLICATE,
        PURErrorCode.IDEMPOTENCY_KEY_CONFLICT,
        PURErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        PURErrorCode.PAYMENT_ALREADY_COMPLETED,
    }
    _422_CODES = {
        PURErrorCode.SUPPLIER_SCOPE_MISMATCH,
        PURErrorCode.REQUEST_BUDGET_EXCEEDED,
        PURErrorCode.SKU_DISABLED,
        PURErrorCode.ORDER_INVALID_STATE_TRANSITION,
        PURErrorCode.ORDER_CANCEL_WITH_RECEIVED,
        PURErrorCode.RECEIPT_OVER_RECEIVED,
        PURErrorCode.RECEIPT_ORDER_INVALID,
        PURErrorCode.RETURN_OVER_RETURNED,
        PURErrorCode.SETTLEMENT_RECONCILE_DIFF_EXCEEDED,
        PURErrorCode.INVOICE_MATCH_DIFF_EXCEEDED,
        PURErrorCode.WMS_INV_INCONSISTENT,
        PURErrorCode.RMQ_INVALID_STATE_TRANSITION,
        PURErrorCode.FRAMEWORK_AGREEMENT_EXPIRED,
        PURErrorCode.FRAMEWORK_AGREEMENT_QTY_EXCEEDED,
        PURErrorCode.APPROVAL_TIMEOUT,
    }
    _500_CODES = {
        PURErrorCode.WMS_RECEIVING_FAILED,
        PURErrorCode.RETURN_INVENTORY_FAILED,
        PURErrorCode.FINANCIAL_API_FAILED,
        PURErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    return 400