"""统一异常处理与错误码体系 - EITP_MT_* / EITP_IAM_* / EITP_INV_* / EITP_MDM_* / EITP_WMS_* 前缀并列共存。"""

from __future__ import annotations

from enum import Enum
from typing import Union

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from structlog import get_logger

logger = get_logger(__name__)


class ErrorCode(str, Enum):
    """EITP 错误码枚举 - 全部以 EITP_MT_ 前缀。"""

    # 租户上下文 (C-ISO-01)
    TENANT_CONTEXT_INVALID = "EITP_MT_TENANT_CONTEXT_INVALID"

    # 租户开通 (5.2.3)
    TENANT_ALREADY_EXISTS = "EITP_MT_TENANT_ALREADY_EXISTS"
    PROVISION_FAILED = "EITP_MT_PROVISION_FAILED"
    DEPROVISION_CONFIRM_REQUIRED = "EITP_MT_DEPROVISION_CONFIRM_REQUIRED"
    DEPROVISION_REQUIRES_DISABLE = "EITP_MT_DEPROVISION_REQUIRES_DISABLE"

    # 层级模型 (5.1.3)
    HIERARCHY_DEPTH_EXCEEDED = "EITP_MT_HIERARCHY_DEPTH_EXCEEDED"
    HIERARCHY_CROSS_TENANT = "EITP_MT_HIERARCHY_CROSS_TENANT"
    HIERARCHY_CIRCULAR_REF = "EITP_MT_HIERARCHY_CIRCULAR_REF"
    HIERARCHY_HAS_ACTIVE_DATA = "EITP_MT_HIERARCHY_HAS_ACTIVE_DATA"

    # 租户隔离 (5.3.3)
    CROSS_TENANT_REF_DENIED = "EITP_MT_CROSS_TENANT_REF_DENIED"

    # 配置 (5.4.3)
    CONFIG_INVALID = "EITP_MT_CONFIG_INVALID"
    CONFIG_INHERIT_CONFLICT = "EITP_MT_CONFIG_INHERIT_CONFLICT"
    FEATURE_HAS_ACTIVE_DATA = "EITP_MT_FEATURE_HAS_ACTIVE_DATA"

    # 业务规则 (5.5.3)
    WORKFLOW_INCOMPLETE = "EITP_MT_WORKFLOW_INCOMPLETE"

    # 集团模式 (5.6.3)
    GROUP_READONLY_VIOLATION = "EITP_MT_GROUP_READONLY_VIOLATION"
    GROUP_SNAPSHOT_DELAYED = "EITP_MT_GROUP_SNAPSHOT_DELAYED"
    MASTER_DATA_CONFLICT = "EITP_MT_MASTER_DATA_CONFLICT"
    MASTER_PROPAGATE_FAILED = "EITP_MT_MASTER_PROPAGATE_FAILED"
    SUBSIDIARY_ISOLATION_VIOLATION = "EITP_MT_SUBSIDIARY_ISOLATION_VIOLATION"

    # 主数据层级继承 (5.9.3)
    MASTER_BASE_READONLY = "EITP_MT_MASTER_BASE_READONLY"
    MASTER_ATTR_CONFLICT = "EITP_MT_MASTER_ATTR_CONFLICT"
    MASTER_NOT_FOUND = "EITP_MT_MASTER_NOT_FOUND"

    # 数据放置与迁移 (5.7.3)
    MIGRATION_IN_PROGRESS = "EITP_MT_MIGRATION_IN_PROGRESS"
    MIGRATION_VERIFY_FAILED = "EITP_MT_MIGRATION_VERIFY_FAILED"
    MIGRATION_TIMEOUT = "EITP_MT_MIGRATION_TIMEOUT"
    PLACEMENT_UNSUPPORTED = "EITP_MT_PLACEMENT_UNSUPPORTED"
    PLACEMENT_RESOURCE_INSUFFICIENT = "EITP_MT_PLACEMENT_RESOURCE_INSUFFICIENT"

    # 备份与恢复 (5.8.3)
    BACKUP_INTEGRITY_FAILED = "EITP_MT_BACKUP_INTEGRITY_FAILED"
    BACKUP_CORRUPTED = "EITP_MT_BACKUP_CORRUPTED"
    BACKUP_STORAGE_INSUFFICIENT = "EITP_MT_BACKUP_STORAGE_INSUFFICIENT"
    RESTORE_FAILED = "EITP_MT_RESTORE_FAILED"
    CROSS_TENANT_RESTORE_DENIED = "EITP_MT_CROSS_TENANT_RESTORE_DENIED"


class IAMErrorCode(str, Enum):
    """EITP IAM 错误码枚举 - 全部以 EITP_IAM_ 前缀。"""

    CREDENTIAL_INVALID = "EITP_IAM_CREDENTIAL_INVALID"
    ACCOUNT_LOCKED = "EITP_IAM_ACCOUNT_LOCKED"
    IP_BANNED = "EITP_IAM_IP_BANNED"
    TENANT_DISABLED = "EITP_IAM_TENANT_DISABLED"
    TENANT_MISMATCH = "EITP_IAM_TENANT_MISMATCH"
    TOKEN_EXPIRED = "EITP_IAM_TOKEN_EXPIRED"
    TOKEN_REVOKED = "EITP_IAM_TOKEN_REVOKED"
    TOKEN_SIGNATURE_INVALID = "EITP_IAM_TOKEN_SIGNATURE_INVALID"
    TOKEN_MISSING = "EITP_IAM_TOKEN_MISSING"
    REFRESH_TOKEN_REVOKED = "EITP_IAM_REFRESH_TOKEN_REVOKED"
    SESSION_EXPIRED = "EITP_IAM_SESSION_EXPIRED"
    PERMISSION_DENIED = "EITP_IAM_PERMISSION_DENIED"
    PERMISSION_MAPPING_MISSING = "EITP_IAM_PERMISSION_MAPPING_MISSING"
    PERMISSION_NOT_FOUND = "EITP_IAM_PERMISSION_NOT_FOUND"
    CROSS_TENANT_ROLE_DENIED = "EITP_IAM_CROSS_TENANT_ROLE_DENIED"
    CROSS_TENANT_REF_DENIED = "EITP_IAM_CROSS_TENANT_REF_DENIED"
    CROSS_TENANT_DATASCOPE_DENIED = "EITP_IAM_CROSS_TENANT_DATASCOPE_DENIED"
    CROSS_TENANT_AUDIT_DENIED = "EITP_IAM_CROSS_TENANT_AUDIT_DENIED"
    BUILTIN_ROLE_PROTECTED = "EITP_IAM_BUILTIN_ROLE_PROTECTED"
    ROLE_DUPLICATE = "EITP_IAM_ROLE_DUPLICATE"
    ROLE_HIERARCHY_VIOLATION = "EITP_IAM_ROLE_HIERARCHY_VIOLATION"
    TENANT_NOT_AUTHORIZED = "EITP_IAM_TENANT_NOT_AUTHORIZED"
    ENTERPRISE_SCOPE_EXCEEDED = "EITP_IAM_ENTERPRISE_SCOPE_EXCEEDED"
    USER_DUPLICATE = "EITP_IAM_USER_DUPLICATE"
    USER_NOT_FOUND = "EITP_IAM_USER_NOT_FOUND"
    OLD_PASSWORD_INVALID = "EITP_IAM_OLD_PASSWORD_INVALID"
    PASSWORD_WEAK = "EITP_IAM_PASSWORD_WEAK"
    PASSWORD_REUSE_DENIED = "EITP_IAM_PASSWORD_REUSE_DENIED"
    PASSWORD_POLICY_BELOW_PLATFORM = "EITP_IAM_PASSWORD_POLICY_BELOW_PLATFORM"
    DATASCOPE_UNRESOLVABLE = "EITP_IAM_DATASCOPE_UNRESOLVABLE"
    DEPT_HAS_ACTIVE_USERS = "EITP_IAM_DEPT_HAS_ACTIVE_USERS"
    DEACTIVATE_CONFIRM_REQUIRED = "EITP_IAM_DEACTIVATE_CONFIRM_REQUIRED"
    TENANT_CONTEXT_MISMATCH = "EITP_IAM_TENANT_CONTEXT_MISMATCH"
    TENANT_TOKEN_MISSING = "EITP_IAM_TENANT_TOKEN_MISSING"
    SERVICE_UNAVAILABLE = "EITP_IAM_SERVICE_UNAVAILABLE"


class INVErrorCode(str, Enum):
    """EITP INV 错误码枚举 - 全部以 EITP_INV_ 前缀。"""

    SKU_DUPLICATE = "EITP_INV_SKU_DUPLICATE"
    SKU_NOT_FOUND = "EITP_INV_SKU_NOT_FOUND"
    PRODUCT_DUPLICATE = "EITP_INV_PRODUCT_DUPLICATE"
    PRODUCT_NOT_FOUND = "EITP_INV_PRODUCT_NOT_FOUND"
    PRODUCT_HAS_ACTIVE_DOCUMENT = "EITP_INV_PRODUCT_HAS_ACTIVE_DOCUMENT"
    CATEGORY_DUPLICATE = "EITP_INV_CATEGORY_DUPLICATE"
    CROSS_TENANT_REF_DENIED = "EITP_INV_CROSS_TENANT_REF_DENIED"
    CROSS_TENANT_AUDIT_DENIED = "EITP_INV_CROSS_TENANT_AUDIT_DENIED"
    WAREHOUSE_DISABLED = "EITP_INV_WAREHOUSE_DISABLED"
    WAREHOUSE_NOT_FOUND = "EITP_INV_WAREHOUSE_NOT_FOUND"
    UNIT_CONVERSION_CONFLICT = "EITP_INV_UNIT_CONVERSION_CONFLICT"
    LOCATION_CAPACITY_EXCEEDED = "EITP_INV_LOCATION_CAPACITY_EXCEEDED"
    LOCATION_NOT_FOUND = "EITP_INV_LOCATION_NOT_FOUND"
    LEDGER_FIELD_REQUIRED = "EITP_INV_LEDGER_FIELD_REQUIRED"
    LEDGER_APPEND_FAILED = "EITP_INV_LEDGER_APPEND_FAILED"
    LEDGER_QUERY_RANGE_EXCEEDED = "EITP_INV_LEDGER_QUERY_RANGE_EXCEEDED"
    BALANCE_SNAPSHOT_INCONSISTENT = "EITP_INV_BALANCE_SNAPSHOT_INCONSISTENT"
    BALANCE_NOT_FOUND = "EITP_INV_BALANCE_NOT_FOUND"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_INV_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_CONFLICT = "EITP_INV_IDEMPOTENCY_KEY_CONFLICT"
    INSUFFICIENT_STOCK = "EITP_INV_INSUFFICIENT_STOCK"
    INSUFFICIENT_AVAILABLE = "EITP_INV_INSUFFICIENT_AVAILABLE"
    NEGATIVE_STOCK_FORCE_DENIED = "EITP_INV_NEGATIVE_STOCK_FORCE_DENIED"
    NEGATIVE_STOCK_APPROVAL_TIMEOUT = "EITP_INV_NEGATIVE_STOCK_APPROVAL_TIMEOUT"
    INVALID_STATE_TRANSITION = "EITP_INV_INVALID_STATE_TRANSITION"
    DOCUMENT_NOT_EDITABLE = "EITP_INV_DOCUMENT_NOT_EDITABLE"
    DOCUMENT_NOT_DELETABLE = "EITP_INV_DOCUMENT_NOT_DELETABLE"
    DOCUMENT_NOT_FOUND = "EITP_INV_DOCUMENT_NOT_FOUND"
    STATE_TRANSITION_DENIED = "EITP_INV_STATE_TRANSITION_DENIED"
    OWNERSHIP_REQUIRED = "EITP_INV_OWNERSHIP_REQUIRED"
    COST_MODEL_NOT_CONFIGURED = "EITP_INV_COST_MODEL_NOT_CONFIGURED"
    COST_MODEL_SWITCH_CONFLICT = "EITP_INV_COST_MODEL_SWITCH_CONFLICT"
    STOCK_BLOCKED_BY_COUNT = "EITP_INV_STOCK_BLOCKED_BY_COUNT"
    COUNT_DIFF_EXCEEDED_THRESHOLD = "EITP_INV_COUNT_DIFF_EXCEEDED_THRESHOLD"
    ADJUST_EXCEED_ONHAND = "EITP_INV_ADJUST_EXCEED_ONHAND"
    BLOCK_EXCEED_ONHAND = "EITP_INV_BLOCK_EXCEED_ONHAND"
    BATCH_SIZE_EXCEEDED = "EITP_INV_BATCH_SIZE_EXCEEDED"
    RESERVATION_NOT_FOUND = "EITP_INV_RESERVATION_NOT_FOUND"
    RESERVATION_ALREADY_RELEASED = "EITP_INV_RESERVATION_ALREADY_RELEASED"
    RESERVATION_EXPIRED = "EITP_INV_RESERVATION_EXPIRED"


class MDMErrorCode(str, Enum):
    """EITP MDM 错误码枚举 - 全部以 EITP_MDM_ 前缀。"""

    GROUP_SKU_DUPLICATE = "EITP_MDM_GROUP_SKU_DUPLICATE"
    GROUP_PRODUCT_NOT_PUBLISHED = "EITP_MDM_GROUP_PRODUCT_NOT_PUBLISHED"
    GROUP_PRODUCT_DISABLED = "EITP_MDM_GROUP_PRODUCT_DISABLED"
    CROSS_ENTERPRISE_REF_DENIED = "EITP_MDM_CROSS_ENTERPRISE_REF_DENIED"
    GROUP_BASE_ATTRIBUTE_READONLY = "EITP_MDM_GROUP_BASE_ATTRIBUTE_READONLY"
    DUPLICATE_REFERENCE = "EITP_MDM_DUPLICATE_REFERENCE"
    SPEC_INSTANCE_INVALID = "EITP_MDM_SPEC_INSTANCE_INVALID"
    ATTRIBUTE_INSTANCE_INVALID = "EITP_MDM_ATTRIBUTE_INSTANCE_INVALID"
    SPEC_TEMPLATE_CYCLE = "EITP_MDM_SPEC_TEMPLATE_CYCLE"
    BARCODE_DUPLICATE = "EITP_MDM_BARCODE_DUPLICATE"
    CATEGORY_CYCLE = "EITP_MDM_CATEGORY_CYCLE"
    CATEGORY_MULTI_BELONG_DENIED = "EITP_MDM_CATEGORY_MULTI_BELONG_DENIED"
    GROUP_CATEGORY_PERMISSION_DENIED = "EITP_MDM_GROUP_CATEGORY_PERMISSION_DENIED"
    UNIT_CONVERSION_CONFLICT = "EITP_MDM_UNIT_CONVERSION_CONFLICT"
    GROUP_UNIT_PERMISSION_DENIED = "EITP_MDM_GROUP_UNIT_PERMISSION_DENIED"
    INVALID_GOVERNANCE_STATE_TRANSITION = "EITP_MDM_INVALID_GOVERNANCE_STATE_TRANSITION"
    GOVERNANCE_REQUEST_NOT_EDITABLE = "EITP_MDM_GOVERNANCE_REQUEST_NOT_EDITABLE"
    GOVERNANCE_APPROVAL_DENIED = "EITP_MDM_GOVERNANCE_APPROVAL_DENIED"
    CROSS_LEVEL_GOVERNANCE_DENIED = "EITP_MDM_CROSS_LEVEL_GOVERNANCE_DENIED"
    VERSION_NOT_FOUND = "EITP_MDM_VERSION_NOT_FOUND"
    GROUP_PRODUCT_HAS_ACTIVE_REFERENCE = "EITP_MDM_GROUP_PRODUCT_HAS_ACTIVE_REFERENCE"
    REFERENCE_HAS_ACTIVE_DOCUMENT = "EITP_MDM_REFERENCE_HAS_ACTIVE_DOCUMENT"
    NEGATIVE_POLICY_PERMISSION_DENIED = "EITP_MDM_NEGATIVE_POLICY_PERMISSION_DENIED"
    CROSS_TENANT_POLICY_DENIED = "EITP_MDM_CROSS_TENANT_POLICY_DENIED"
    NEGATIVE_POLICY_REASON_REQUIRED = "EITP_MDM_NEGATIVE_POLICY_REASON_REQUIRED"
    NEGATIVE_POLICY_DEFAULT_MUST_STRICT = "EITP_MDM_NEGATIVE_POLICY_DEFAULT_MUST_STRICT"
    LEDGER_TRIGGER_GUARD_FAILED = "EITP_MDM_LEDGER_TRIGGER_GUARD_FAILED"
    IDEMPOTENCY_FAIL_SAFE_VIOLATION = "EITP_MDM_IDEMPOTENCY_FAIL_SAFE_VIOLATION"
    INV_REGRESSION_FAILED = "EITP_MDM_INV_REGRESSION_FAILED"
    PRODUCT_NOT_AVAILABLE = "EITP_MDM_PRODUCT_NOT_AVAILABLE"
    SERVICE_UNAVAILABLE = "EITP_MDM_SERVICE_UNAVAILABLE"
    DIRECT_ACCESS_DENIED = "EITP_MDM_DIRECT_ACCESS_DENIED"
    GROUP_CATALOG_PERMISSION_DENIED = "EITP_MDM_GROUP_CATALOG_PERMISSION_DENIED"


class WMSErrorCode(str, Enum):
    """EITP WMS 错误码枚举 - 全部以 EITP_WMS_ 前缀。"""

    LOCATION_CODE_DUPLICATE = "EITP_WMS_LOCATION_CODE_DUPLICATE"
    LOCATION_CAPACITY_EXCEEDED = "EITP_WMS_LOCATION_CAPACITY_EXCEEDED"
    LOCATION_DISABLED = "EITP_WMS_LOCATION_DISABLED"
    LOCATION_NOT_FOUND = "EITP_WMS_LOCATION_NOT_FOUND"
    ZONE_FUNCTION_MISMATCH = "EITP_WMS_ZONE_FUNCTION_MISMATCH"
    ZONE_NOT_FOUND = "EITP_WMS_ZONE_NOT_FOUND"
    AREA_NOT_FOUND = "EITP_WMS_AREA_NOT_FOUND"
    HIERARCHY_CYCLE = "EITP_WMS_HIERARCHY_CYCLE"
    DIRECT_POSITION_MODIFY_DENIED = "EITP_WMS_DIRECT_POSITION_MODIFY_DENIED"
    INV_INCONSISTENT = "EITP_WMS_INV_INCONSISTENT"
    RECEIVING_OVER_RECEIVED = "EITP_WMS_RECEIVING_OVER_RECEIVED"
    RECEIVING_ZONE_INVALID = "EITP_WMS_RECEIVING_ZONE_INVALID"
    RECEIVING_NOT_FOUND = "EITP_WMS_RECEIVING_NOT_FOUND"
    RECEIVING_ALREADY_COMPLETED = "EITP_WMS_RECEIVING_ALREADY_COMPLETED"
    PUTAWAY_CAPACITY_EXCEEDED = "EITP_WMS_PUTAWAY_CAPACITY_EXCEEDED"
    PUTAWAY_LOCATION_DISABLED = "EITP_WMS_PUTAWAY_LOCATION_DISABLED"
    PUTAWAY_ZONE_NOT_STORAGE = "EITP_WMS_PUTAWAY_ZONE_NOT_STORAGE"
    PUTAWAY_NOT_FOUND = "EITP_WMS_PUTAWAY_NOT_FOUND"
    PUTAWAY_ALREADY_COMPLETED = "EITP_WMS_PUTAWAY_ALREADY_COMPLETED"
    PICKING_INSUFFICIENT_AVAILABLE = "EITP_WMS_PICKING_INSUFFICIENT_AVAILABLE"
    PICKING_STATUS_UNAVAILABLE = "EITP_WMS_PICKING_STATUS_UNAVAILABLE"
    PICKING_QTY_MISMATCH = "EITP_WMS_PICKING_QTY_MISMATCH"
    PICKING_NOT_FOUND = "EITP_WMS_PICKING_NOT_FOUND"
    PICKING_ALREADY_COMPLETED = "EITP_WMS_PICKING_ALREADY_COMPLETED"
    TRANSFER_CROSS_WAREHOUSE = "EITP_WMS_TRANSFER_CROSS_WAREHOUSE"
    TRANSFER_INSUFFICIENT_SOURCE = "EITP_WMS_TRANSFER_INSUFFICIENT_SOURCE"
    TRANSFER_TARGET_CAPACITY_EXCEEDED = "EITP_WMS_TRANSFER_TARGET_CAPACITY_EXCEEDED"
    TRANSFER_NOT_FOUND = "EITP_WMS_TRANSFER_NOT_FOUND"
    SHIPPING_PICKING_NOT_COMPLETED = "EITP_WMS_SHIPPING_PICKING_NOT_COMPLETED"
    SHIPPING_ZONE_INVALID = "EITP_WMS_SHIPPING_ZONE_INVALID"
    SHIPPING_NOT_FOUND = "EITP_WMS_SHIPPING_NOT_FOUND"
    SHIPPING_ALREADY_COMPLETED = "EITP_WMS_SHIPPING_ALREADY_COMPLETED"
    TASK_INVALID_STATE_TRANSITION = "EITP_WMS_TASK_INVALID_STATE_TRANSITION"
    TASK_ASSIGNMENT_DENIED = "EITP_WMS_TASK_ASSIGNMENT_DENIED"
    TASK_NOT_FOUND = "EITP_WMS_TASK_NOT_FOUND"
    TASK_ALREADY_COMPLETED = "EITP_WMS_TASK_ALREADY_COMPLETED"
    DIRECT_INVENTORY_MODIFY_DENIED = "EITP_WMS_DIRECT_INVENTORY_MODIFY_DENIED"
    INV_TRANSACTION_FAILED = "EITP_WMS_INV_TRANSACTION_FAILED"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_WMS_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_CONFLICT = "EITP_WMS_IDEMPOTENCY_KEY_CONFLICT"
    SKU_NOT_FOUND = "EITP_WMS_SKU_NOT_FOUND"
    WAREHOUSE_NOT_FOUND = "EITP_WMS_WAREHOUSE_NOT_FOUND"
    WAREHOUSE_DISABLED = "EITP_WMS_WAREHOUSE_DISABLED"
    CROSS_TENANT_REF_DENIED = "EITP_WMS_CROSS_TENANT_REF_DENIED"
    OWNERSHIP_REQUIRED = "EITP_WMS_OWNERSHIP_REQUIRED"
    BATCH_REQUIRED = "EITP_WMS_BATCH_REQUIRED"
    EXPIRY_WARNING = "EITP_WMS_EXPIRY_WARNING"
    SERVICE_UNAVAILABLE = "EITP_WMS_SERVICE_UNAVAILABLE"


class PURErrorCode(str, Enum):
    """EITP PUR 错误码枚举 - 全部以 EITP_PUR_ 前缀。"""

    SUPPLIER_CODE_DUPLICATE = "EITP_PUR_SUPPLIER_CODE_DUPLICATE"
    SUPPLIER_NOT_ACTIVE = "EITP_PUR_SUPPLIER_NOT_ACTIVE"
    SUPPLIER_DISABLED = "EITP_PUR_SUPPLIER_DISABLED"
    SUPPLIER_SCOPE_MISMATCH = "EITP_PUR_SUPPLIER_SCOPE_MISMATCH"
    SUPPLIER_NOT_FOUND = "EITP_PUR_SUPPLIER_NOT_FOUND"
    CROSS_TENANT_SUPPLIER_DENIED = "EITP_PUR_CROSS_TENANT_SUPPLIER_DENIED"
    REQUEST_BUDGET_EXCEEDED = "EITP_PUR_REQUEST_BUDGET_EXCEEDED"
    REQUEST_NOT_APPROVED = "EITP_PUR_REQUEST_NOT_APPROVED"
    REQUEST_NOT_FOUND = "EITP_PUR_REQUEST_NOT_FOUND"
    SKU_DISABLED = "EITP_PUR_SKU_DISABLED"
    SKU_NOT_FOUND = "EITP_PUR_SKU_NOT_FOUND"
    ORDER_INVALID_STATE_TRANSITION = "EITP_PUR_ORDER_INVALID_STATE_TRANSITION"
    ORDER_NOT_APPROVED = "EITP_PUR_ORDER_NOT_APPROVED"
    ORDER_CANCEL_WITH_RECEIVED = "EITP_PUR_ORDER_CANCEL_WITH_RECEIVED"
    ORDER_NOT_FOUND = "EITP_PUR_ORDER_NOT_FOUND"
    ORDER_LINE_NOT_FOUND = "EITP_PUR_ORDER_LINE_NOT_FOUND"
    RECEIPT_OVER_RECEIVED = "EITP_PUR_RECEIPT_OVER_RECEIVED"
    RECEIPT_ORDER_INVALID = "EITP_PUR_RECEIPT_ORDER_INVALID"
    RECEIPT_NOT_FOUND = "EITP_PUR_RECEIPT_NOT_FOUND"
    WMS_RECEIVING_FAILED = "EITP_PUR_WMS_RECEIVING_FAILED"
    DIRECT_INVENTORY_MODIFY_DENIED = "EITP_PUR_DIRECT_INVENTORY_MODIFY_DENIED"
    RETURN_OVER_RETURNED = "EITP_PUR_RETURN_OVER_RETURNED"
    RETURN_INVENTORY_FAILED = "EITP_PUR_RETURN_INVENTORY_FAILED"
    RETURN_NOT_APPROVED = "EITP_PUR_RETURN_NOT_APPROVED"
    RETURN_NOT_FOUND = "EITP_PUR_RETURN_NOT_FOUND"
    SETTLEMENT_RECONCILE_DIFF_EXCEEDED = "EITP_PUR_SETTLEMENT_RECONCILE_DIFF_EXCEEDED"
    SETTLEMENT_NOT_FOUND = "EITP_PUR_SETTLEMENT_NOT_FOUND"
    INVOICE_MATCH_DIFF_EXCEEDED = "EITP_PUR_INVOICE_MATCH_DIFF_EXCEEDED"
    INVOICE_NOT_FOUND = "EITP_PUR_INVOICE_NOT_FOUND"
    FINANCIAL_API_FAILED = "EITP_PUR_FINANCIAL_API_FAILED"
    DIRECT_COST_MODIFY_DENIED = "EITP_PUR_DIRECT_COST_MODIFY_DENIED"
    WMS_INV_INCONSISTENT = "EITP_PUR_WMS_INV_INCONSISTENT"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_PUR_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_CONFLICT = "EITP_PUR_IDEMPOTENCY_KEY_CONFLICT"
    CROSS_TENANT_REF_DENIED = "EITP_PUR_CROSS_TENANT_REF_DENIED"
    OWNERSHIP_REQUIRED = "EITP_PUR_OWNERSHIP_REQUIRED"
    BUDGET_NOT_FOUND = "EITP_PUR_BUDGET_NOT_FOUND"
    APPROVAL_TIMEOUT = "EITP_PUR_APPROVAL_TIMEOUT"
    PAYMENT_NOT_FOUND = "EITP_PUR_PAYMENT_NOT_FOUND"
    PAYMENT_ALREADY_COMPLETED = "EITP_PUR_PAYMENT_ALREADY_COMPLETED"
    ASN_NOT_FOUND = "EITP_PUR_ASN_NOT_FOUND"
    QUOTATION_NOT_FOUND = "EITP_PUR_QUOTATION_NOT_FOUND"
    EVALUATION_NOT_FOUND = "EITP_PUR_EVALUATION_NOT_FOUND"
    RMQ_INVALID_STATE_TRANSITION = "EITP_PUR_RMQ_INVALID_STATE_TRANSITION"
    FRAMEWORK_AGREEMENT_EXPIRED = "EITP_PUR_FRAMEWORK_AGREEMENT_EXPIRED"
    FRAMEWORK_AGREEMENT_QTY_EXCEEDED = "EITP_PUR_FRAMEWORK_AGREEMENT_QTY_EXCEEDED"
    PORTAL_PERMISSION_DENIED = "EITP_PUR_PORTAL_PERMISSION_DENIED"
    SERVICE_UNAVAILABLE = "EITP_PUR_SERVICE_UNAVAILABLE"


class SALErrorCode(str, Enum):
    """EITP SAL 错误码枚举 - 全部以 EITP_SAL_ 前缀。"""

    CUSTOMER_CODE_DUPLICATE = "EITP_SAL_CUSTOMER_CODE_DUPLICATE"
    CUSTOMER_NOT_ACTIVE = "EITP_SAL_CUSTOMER_NOT_ACTIVE"
    CUSTOMER_DISABLED = "EITP_SAL_CUSTOMER_DISABLED"
    CUSTOMER_NOT_FOUND = "EITP_SAL_CUSTOMER_NOT_FOUND"
    CROSS_TENANT_CUSTOMER_DENIED = "EITP_SAL_CROSS_TENANT_CUSTOMER_DENIED"
    CREDIT_LIMIT_EXCEEDED = "EITP_SAL_CREDIT_LIMIT_EXCEEDED"
    CREDIT_CONFIG_NOT_FOUND = "EITP_SAL_CREDIT_CONFIG_NOT_FOUND"
    CREDIT_CONCURRENT_CONFLICT = "EITP_SAL_CREDIT_CONCURRENT_CONFLICT"
    QUOTATION_NOT_APPROVED = "EITP_SAL_QUOTATION_NOT_APPROVED"
    QUOTATION_EXPIRED = "EITP_SAL_QUOTATION_EXPIRED"
    QUOTATION_INVALID_STATE_TRANSITION = "EITP_SAL_QUOTATION_INVALID_STATE_TRANSITION"
    QUOTATION_NOT_FOUND = "EITP_SAL_QUOTATION_NOT_FOUND"
    SKU_DISABLED = "EITP_SAL_SKU_DISABLED"
    SKU_NOT_FOUND = "EITP_SAL_SKU_NOT_FOUND"
    ORDER_INVALID_STATE_TRANSITION = "EITP_SAL_ORDER_INVALID_STATE_TRANSITION"
    ORDER_NOT_APPROVED = "EITP_SAL_ORDER_NOT_APPROVED"
    ORDER_CANCEL_WITH_SHIPPED = "EITP_SAL_ORDER_CANCEL_WITH_SHIPPED"
    ORDER_NOT_FOUND = "EITP_SAL_ORDER_NOT_FOUND"
    RESERVATION_FAILED = "EITP_SAL_RESERVATION_FAILED"
    INSUFFICIENT_STOCK = "EITP_SAL_INSUFFICIENT_STOCK"
    SHIPMENT_OVER_SHIPPED = "EITP_SAL_SHIPMENT_OVER_SHIPPED"
    SHIPMENT_ORDER_INVALID = "EITP_SAL_SHIPMENT_ORDER_INVALID"
    SHIPMENT_NOT_FOUND = "EITP_SAL_SHIPMENT_NOT_FOUND"
    WMS_PICKING_FAILED = "EITP_SAL_WMS_PICKING_FAILED"
    WMS_SHIPPING_FAILED = "EITP_SAL_WMS_SHIPPING_FAILED"
    RETURN_OVER_RETURNED = "EITP_SAL_RETURN_OVER_RETURNED"
    RETURN_RECEIVING_FAILED = "EITP_SAL_RETURN_RECEIVING_FAILED"
    RETURN_NOT_APPROVED = "EITP_SAL_RETURN_NOT_APPROVED"
    RETURN_NOT_FOUND = "EITP_SAL_RETURN_NOT_FOUND"
    SETTLEMENT_RECONCILE_DIFF_EXCEEDED = "EITP_SAL_SETTLEMENT_RECONCILE_DIFF_EXCEEDED"
    SETTLEMENT_NOT_FOUND = "EITP_SAL_SETTLEMENT_NOT_FOUND"
    INVOICE_MATCH_DIFF_EXCEEDED = "EITP_SAL_INVOICE_MATCH_DIFF_EXCEEDED"
    INVOICE_NOT_FOUND = "EITP_SAL_INVOICE_NOT_FOUND"
    FINANCIAL_API_FAILED = "EITP_SAL_FINANCIAL_API_FAILED"
    PAYMENT_FAILED = "EITP_SAL_PAYMENT_FAILED"
    PAYMENT_NOT_FOUND = "EITP_SAL_PAYMENT_NOT_FOUND"
    DIRECT_INVENTORY_MODIFY_DENIED = "EITP_SAL_DIRECT_INVENTORY_MODIFY_DENIED"
    DIRECT_REVENUE_MODIFY_DENIED = "EITP_SAL_DIRECT_REVENUE_MODIFY_DENIED"
    DIRECT_RESERVATION_MODIFY_DENIED = "EITP_SAL_DIRECT_RESERVATION_MODIFY_DENIED"
    WMS_INV_INCONSISTENT = "EITP_SAL_WMS_INV_INCONSISTENT"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_SAL_IDEMPOTENCY_KEY_REQUIRED"
    CROSS_TENANT_REF_DENIED = "EITP_SAL_CROSS_TENANT_REF_DENIED"
    OWNERSHIP_REQUIRED = "EITP_SAL_OWNERSHIP_REQUIRED"
    APPROVAL_TIMEOUT = "EITP_SAL_APPROVAL_TIMEOUT"
    PRICING_NOT_FOUND = "EITP_SAL_PRICING_NOT_FOUND"
    PROMOTION_INVALID = "EITP_SAL_PROMOTION_INVALID"
    PORTAL_PERMISSION_DENIED = "EITP_SAL_PORTAL_PERMISSION_DENIED"
    CONTRACT_QTY_EXCEEDED = "EITP_SAL_CONTRACT_QTY_EXCEEDED"
    SERVICE_UNAVAILABLE = "EITP_SAL_SERVICE_UNAVAILABLE"


class PLTErrorCode(str, Enum):
    """EITP PLT 错误码枚举 - 全部以 EITP_PLT_ 前缀。"""

    AUDIT_UPDATE_FORBIDDEN = "EITP_PLT_AUDIT_UPDATE_FORBIDDEN"
    AUDIT_DELETE_FORBIDDEN = "EITP_PLT_AUDIT_DELETE_FORBIDDEN"
    AUDIT_TAMPER_DETECTED = "EITP_PLT_AUDIT_TAMPER_DETECTED"
    AUDIT_CROSS_TENANT_DENIED = "EITP_PLT_AUDIT_CROSS_TENANT_DENIED"
    AUDIT_NOT_FOUND = "EITP_PLT_AUDIT_NOT_FOUND"
    AUDIT_HASH_CHAIN_BROKEN = "EITP_PLT_AUDIT_HASH_CHAIN_BROKEN"
    AUDIT_RETENTION_INVALID = "EITP_PLT_AUDIT_RETENTION_INVALID"
    AUDIT_ARCHIVE_FAILED = "EITP_PLT_AUDIT_ARCHIVE_FAILED"
    AUDIT_EXPORT_DENIED = "EITP_PLT_AUDIT_EXPORT_DENIED"
    OUTBOX_DELIVERY_FAILED = "EITP_PLT_OUTBOX_DELIVERY_FAILED"
    OUTBOX_MAX_ATTEMPTS_EXCEEDED = "EITP_PLT_OUTBOX_MAX_ATTEMPTS_EXCEEDED"
    OUTBOX_EVENT_NOT_FOUND = "EITP_PLT_OUTBOX_EVENT_NOT_FOUND"
    OUTBOX_ALREADY_DELIVERED = "EITP_PLT_OUTBOX_ALREADY_DELIVERED"
    SAGA_COMPENSATION_FAILED = "EITP_PLT_SAGA_COMPENSATION_FAILED"
    SAGA_NOT_FOUND = "EITP_PLT_SAGA_NOT_FOUND"
    SAGA_STEP_FAILED = "EITP_PLT_SAGA_STEP_FAILED"
    SAGA_INVALID_TRANSITION = "EITP_PLT_SAGA_INVALID_TRANSITION"
    SAGA_MANUAL_INTERVENTION_REQUIRED = "EITP_PLT_SAGA_MANUAL_INTERVENTION_REQUIRED"
    IDEMPOTENCY_CONFLICT = "EITP_PLT_IDEMPOTENCY_CONFLICT"
    IDEMPOTENCY_KEY_FORMAT_VIOLATION = "EITP_PLT_IDEMPOTENCY_KEY_FORMAT_VIOLATION"
    IDEMPOTENCY_KEY_REQUIRED = "EITP_PLT_IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_EXPIRED = "EITP_PLT_IDEMPOTENCY_EXPIRED"
    PERMISSION_APPROVER_CONFLICT = "EITP_PLT_PERMISSION_APPROVER_CONFLICT"
    PERMISSION_MATRIX_CONFLICT = "EITP_PLT_PERMISSION_MATRIX_CONFLICT"
    PERMISSION_NOT_FOUND = "EITP_PLT_PERMISSION_NOT_FOUND"
    PERMISSION_APPROVAL_REJECTED = "EITP_PLT_PERMISSION_APPROVAL_REJECTED"
    PERMISSION_MENU_CYCLE = "EITP_PLT_PERMISSION_MENU_CYCLE"
    TENANT_QUOTA_EXCEEDED = "EITP_PLT_TENANT_QUOTA_EXCEEDED"
    TENANT_ARCHIVED = "EITP_PLT_TENANT_ARCHIVED"
    TENANT_FROZEN = "EITP_PLT_TENANT_FROZEN"
    TENANT_INIT_FAILED = "EITP_PLT_TENANT_INIT_FAILED"
    TENANT_INVALID_TRANSITION = "EITP_PLT_TENANT_INVALID_TRANSITION"
    TENANT_NOT_FOUND = "EITP_PLT_TENANT_NOT_FOUND"
    CONFIG_VALUE_INVALID = "EITP_PLT_CONFIG_VALUE_INVALID"
    CONFIG_NOT_FOUND = "EITP_PLT_CONFIG_NOT_FOUND"
    CONFIG_VERSION_CONFLICT = "EITP_PLT_CONFIG_VERSION_CONFLICT"
    CONFIG_DECRYPT_FAILED = "EITP_PLT_CONFIG_DECRYPT_FAILED"
    CONFIG_GRAY_RELEASE_INVALID = "EITP_PLT_CONFIG_GRAY_RELEASE_INVALID"
    RATE_LIMIT_EXCEEDED = "EITP_PLT_RATE_LIMIT_EXCEEDED"
    API_VERSION_DEPRECATED = "EITP_PLT_API_VERSION_DEPRECATED"
    API_VERSION_SUNSET = "EITP_PLT_API_VERSION_SUNSET"
    API_CONTRACT_NOT_FOUND = "EITP_PLT_API_CONTRACT_NOT_FOUND"
    JOB_TIMEOUT = "EITP_PLT_JOB_TIMEOUT"
    JOB_NOT_FOUND = "EITP_PLT_JOB_NOT_FOUND"
    JOB_CONFLICT = "EITP_PLT_JOB_CONFLICT"
    JOB_DISABLED = "EITP_PLT_JOB_DISABLED"
    JOB_HANDLER_NOT_FOUND = "EITP_PLT_JOB_HANDLER_NOT_FOUND"
    CERT_GATE_NOT_PASSED = "EITP_PLT_CERT_GATE_NOT_PASSED"
    PERFORMANCE_REGRESSION = "EITP_PLT_PERFORMANCE_REGRESSION"
    PERFORMANCE_BASELINE_NOT_FOUND = "EITP_PLT_PERFORMANCE_BASELINE_NOT_FOUND"
    ERRORCODE_DUPLICATE = "EITP_PLT_ERRORCODE_DUPLICATE"
    ERRORCODE_NOT_REGISTERED = "EITP_PLT_ERRORCODE_NOT_REGISTERED"
    DB_UNAVAILABLE = "EITP_PLT_DB_UNAVAILABLE"
    DB_RLS_VIOLATION = "EITP_PLT_DB_RLS_VIOLATION"
    UPSTREAM_TIMEOUT = "EITP_PLT_UPSTREAM_TIMEOUT"
    UPSTREAM_UNAVAILABLE = "EITP_PLT_UPSTREAM_UNAVAILABLE"
    ROLE_MIGRATION_CONFLICT = "EITP_PLT_ROLE_MIGRATION_CONFLICT"
    ROLE_PERMISSION_DENIED = "EITP_PLT_ROLE_PERMISSION_DENIED"
    OBSERVABILITY_METRIC_INVALID = "EITP_PLT_OBSERVABILITY_METRIC_INVALID"
    OBSERVABILITY_TRACE_NOT_FOUND = "EITP_PLT_OBSERVABILITY_TRACE_NOT_FOUND"
    CICD_PIPELINE_FAILED = "EITP_PLT_CICD_PIPELINE_FAILED"
    CICD_DEPLOY_ROLLBACK_FAILED = "EITP_PLT_CICD_DEPLOY_ROLLBACK_FAILED"
    HEALTH_CHECK_FAILED = "EITP_PLT_HEALTH_CHECK_FAILED"
    INTERNAL_ERROR = "EITP_PLT_INTERNAL_ERROR"


class PRODErrorCode(str, Enum):
    """EITP PROD 错误码枚举 - 全部以 EITP_PROD_ 前缀。"""

    CORE_FREEZE_VIOLATED = "EITP_PROD_CORE_FREEZE_VIOLATED"
    VERIFICATION_ENV_FORBIDDEN = "EITP_PROD_VERIFICATION_ENV_FORBIDDEN"
    VERIFICATION_NOT_FOUND = "EITP_PROD_VERIFICATION_NOT_FOUND"
    VERIFICATION_ALREADY_RUNNING = "EITP_PROD_VERIFICATION_ALREADY_RUNNING"
    VERIFICATION_PREREQUISITE_NOT_MET = "EITP_PROD_VERIFICATION_PREREQUISITE_NOT_MET"
    BASELINE_INSUFFICIENT_SAMPLES = "EITP_PROD_BASELINE_INSUFFICIENT_SAMPLES"
    BASELINE_LOW_CONFIDENCE = "EITP_PROD_BASELINE_LOW_CONFIDENCE"
    BASELINE_LATENCY_DEGRADED = "EITP_PROD_BASELINE_LATENCY_DEGRADED"
    CONCURRENT_CROSS_TENANT_POLLUTION = "EITP_PROD_CONCURRENT_CROSS_TENANT_POLLUTION"
    CONCURRENT_DATA_INCONSISTENT = "EITP_PROD_CONCURRENT_DATA_INCONSISTENT"
    CONCURRENT_DEADLOCK_DETECTED = "EITP_PROD_CONCURRENT_DEADLOCK_DETECTED"
    CONNPOOL_LEAK_DETECTED = "EITP_PROD_CONNPOOL_LEAK_DETECTED"
    CONNPOOL_EXHAUSTED_NO_TIMEOUT = "EITP_PROD_CONNPOOL_EXHAUSTED_NO_TIMEOUT"
    CACHE_BREAKDOWN_UNPROTECTED = "EITP_PROD_CACHE_BREAKDOWN_UNPROTECTED"
    CACHE_KEY_PREFIX_VIOLATION = "EITP_PROD_CACHE_KEY_PREFIX_VIOLATION"
    CACHE_NO_FALLBACK = "EITP_PROD_CACHE_NO_FALLBACK"
    OUTBOX_EVENT_LOST = "EITP_PROD_OUTBOX_EVENT_LOST"
    OUTBOX_ORDER_VIOLATION = "EITP_PROD_OUTBOX_ORDER_VIOLATION"
    OUTBOX_DEADLETTER_NO_ALERT = "EITP_PROD_OUTBOX_DEADLETTER_NO_ALERT"
    SAGA_COMPENSATION_INCONSISTENT = "EITP_PROD_SAGA_COMPENSATION_INCONSISTENT"
    SAGA_COMPENSATION_NOT_IDEMPOTENT = "EITP_PROD_SAGA_COMPENSATION_NOT_IDEMPOTENT"
    SAGA_COMPENSATION_NO_ALERT = "EITP_PROD_SAGA_COMPENSATION_NO_ALERT"
    JOB_DEFINITION_LOST = "EITP_PROD_JOB_DEFINITION_LOST"
    JOB_MISFIRE_NOT_IDEMPOTENT = "EITP_PROD_JOB_MISFIRE_NOT_IDEMPOTENT"
    JOB_SCHEDULE_DRIFT = "EITP_PROD_JOB_SCHEDULE_DRIFT"
    ALERT_NOT_FIRED = "EITP_PROD_ALERT_NOT_FIRED"
    ALERT_NOTIFICATION_NOT_DELIVERED = "EITP_PROD_ALERT_NOTIFICATION_NOT_DELIVERED"
    ALERT_COVERAGE_GAP = "EITP_PROD_ALERT_COVERAGE_GAP"
    TRACE_BROKEN = "EITP_PROD_TRACE_BROKEN"
    TRACE_ID_INCONSISTENT = "EITP_PROD_TRACE_ID_INCONSISTENT"
    TRACE_EXPLOSION = "EITP_PROD_TRACE_EXPLOSION"
    BACKUP_CORRUPTED = "EITP_PROD_BACKUP_CORRUPTED"
    RESTORE_DATA_MISMATCH = "EITP_PROD_RESTORE_DATA_MISMATCH"
    PITR_PRECISION_INSUFFICIENT = "EITP_PROD_PITR_PRECISION_INSUFFICIENT"
    BACKUP_NOT_ENCRYPTED = "EITP_PROD_BACKUP_NOT_ENCRYPTED"
    DR_DATA_LOSS = "EITP_PROD_DR_DATA_LOSS"
    DR_RTO_EXCEEDED = "EITP_PROD_DR_RTO_EXCEEDED"
    DR_SINGLE_AUTHORIZATION_DENIED = "EITP_PROD_DR_SINGLE_AUTHORIZATION_DENIED"
    DR_API_UNAVAILABLE = "EITP_PROD_DR_API_UNAVAILABLE"
    CONTAINER_RECOVERY_TIMEOUT = "EITP_PROD_CONTAINER_RECOVERY_TIMEOUT"
    INFLIGHT_REQUEST_DROPPED = "EITP_PROD_INFLIGHT_REQUEST_DROPPED"
    DEPENDENCY_ORDER_VIOLATION = "EITP_PROD_DEPENDENCY_ORDER_VIOLATION"
    RATE_LIMIT_NOT_EFFECTIVE = "EITP_PROD_RATE_LIMIT_NOT_EFFECTIVE"
    RATE_LIMIT_CROSS_TENANT = "EITP_PROD_RATE_LIMIT_CROSS_TENANT"
    RATE_LIMIT_FALSE_POSITIVE = "EITP_PROD_RATE_LIMIT_FALSE_POSITIVE"
    LARGE_TENANT_QUERY_SLOW = "EITP_PROD_LARGE_TENANT_QUERY_SLOW"
    LARGE_TENANT_LOW_INDEX_HIT = "EITP_PROD_LARGE_TENANT_LOW_INDEX_HIT"
    LARGE_TENANT_ISOLATION_DEGRADED = "EITP_PROD_LARGE_TENANT_ISOLATION_DEGRADED"
    REGRESSION_BIZ_FAILED = "EITP_PROD_REGRESSION_BIZ_FAILED"
    REGRESSION_SEC_FAILED = "EITP_PROD_REGRESSION_SEC_FAILED"
    REGRESSION_PLT_FAILED = "EITP_PROD_REGRESSION_PLT_FAILED"
    SEC_RECERT_PREREQUISITE_NOT_MET = "EITP_PROD_SEC_RECERT_PREREQUISITE_NOT_MET"
    SEC_RECERT_FAILED = "EITP_PROD_SEC_RECERT_FAILED"
    SEC_RECERT_DEGRADED = "EITP_PROD_SEC_RECERT_DEGRADED"
    DOSSIER_PREREQUISITE_NOT_MET = "EITP_PROD_DOSSIER_PREREQUISITE_NOT_MET"
    DOSSIER_EVIDENCE_MISSING = "EITP_PROD_DOSSIER_EVIDENCE_MISSING"
    DOSSIER_EVIDENCE_TAMPERED = "EITP_PROD_DOSSIER_EVIDENCE_TAMPERED"
    DOSSIER_UNAUTHORIZED_SIGNER = "EITP_PROD_DOSSIER_UNAUTHORIZED_SIGNER"
    DOSSIER_ALREADY_SIGNED = "EITP_PROD_DOSSIER_ALREADY_SIGNED"
    DOSSIER_EXPIRED = "EITP_PROD_DOSSIER_EXPIRED"
    DOSSIER_NOT_FOUND = "EITP_PROD_DOSSIER_NOT_FOUND"
    EVIDENCE_NOT_FOUND = "EITP_PROD_EVIDENCE_NOT_FOUND"
    EVIDENCE_HASH_MISMATCH = "EITP_PROD_EVIDENCE_HASH_MISMATCH"
    INTERNAL_ERROR = "EITP_PROD_INTERNAL_ERROR"


class SECErrorCode(str, Enum):
    """EITP SEC 错误码枚举 - 全部以 EITP_SEC_ 前缀。"""

    JWT_TENANT_MISMATCH = "EITP_SEC_JWT_TENANT_MISMATCH"
    TENANT_TOKEN_JWT_INCONSISTENT = "EITP_SEC_TENANT_TOKEN_JWT_INCONSISTENT"
    CONTEXT_INCONSISTENT = "EITP_SEC_CONTEXT_INCONSISTENT"
    DATASCOPE_VIOLATION = "EITP_SEC_DATASCOPE_VIOLATION"
    API_CROSS_TENANT_ACCESS = "EITP_SEC_API_CROSS_TENANT_ACCESS"
    APP_CROSS_TENANT_COMMAND = "EITP_SEC_APP_CROSS_TENANT_COMMAND"
    REPO_MISSING_TENANT_FILTER = "EITP_SEC_REPO_MISSING_TENANT_FILTER"
    JOIN_CROSS_TENANT_LEAK = "EITP_SEC_JOIN_CROSS_TENANT_LEAK"
    JOIN_MISSING_TENANT_FILTER = "EITP_SEC_JOIN_MISSING_TENANT_FILTER"
    JOIN_TENANT_ID_INCONSISTENT = "EITP_SEC_JOIN_TENANT_ID_INCONSISTENT"
    AGGREGATE_REVERSIBLE = "EITP_SEC_AGGREGATE_REVERSIBLE"
    REDIS_KEY_VIOLATION = "EITP_SEC_REDIS_KEY_VIOLATION"
    REDIS_KEY_PREFIX_MISSING = "EITP_SEC_REDIS_KEY_PREFIX_MISSING"
    REDIS_UNREACHABLE = "EITP_SEC_REDIS_UNREACHABLE"
    REDIS_SCAN_TIMEOUT = "EITP_SEC_REDIS_SCAN_TIMEOUT"
    REDIS_KEY_CLEANUP_FAILED = "EITP_SEC_REDIS_KEY_CLEANUP_FAILED"
    PLATFORM_ADMIN_BUSINESS_DATA_DENIED = "EITP_SEC_PLATFORM_ADMIN_BUSINESS_DATA_DENIED"
    PLATFORM_ADMIN_BUSINESS_WRITE_DENIED = "EITP_SEC_PLATFORM_ADMIN_BUSINESS_WRITE_DENIED"
    APPLICATION_NOT_AUDITED = "EITP_SEC_APPLICATION_NOT_AUDITED"
    CERT_PREREQUISITE_NOT_MET = "EITP_SEC_CERT_PREREQUISITE_NOT_MET"
    CERT_ISSUE_FAILED = "EITP_SEC_CERT_ISSUE_FAILED"
    CERT_SIGN_FAILED = "EITP_SEC_CERT_SIGN_FAILED"
    CERT_PERSIST_FAILED = "EITP_SEC_CERT_PERSIST_FAILED"
    CERT_REVOKED_USED = "EITP_SEC_CERT_REVOKED_USED"
    CERT_ITEM_TIMEOUT = "EITP_SEC_CERT_ITEM_TIMEOUT"
    EVIDENCE_MISSING = "EITP_SEC_EVIDENCE_MISSING"
    ATTACK_VECTOR_SETUP_FAILED = "EITP_SEC_ATTACK_VECTOR_SETUP_FAILED"
    TEST_TENANT_SETUP_FAILED = "EITP_SEC_TEST_TENANT_SETUP_FAILED"
    TEST_DATA_CLEANUP_FAILED = "EITP_SEC_TEST_DATA_CLEANUP_FAILED"
    MATRIX_CONFIG_INVALID = "EITP_SEC_MATRIX_CONFIG_INVALID"
    CERT_ALREADY_RUNNING = "EITP_SEC_CERT_ALREADY_RUNNING"
    REPORT_NOT_FOUND = "EITP_SEC_REPORT_NOT_FOUND"
    REPORT_ACCESS_DENIED = "EITP_SEC_REPORT_ACCESS_DENIED"
    REPORT_PERSIST_FAILED = "EITP_SEC_REPORT_PERSIST_FAILED"
    AUDIT_TAMPER_ATTEMPT = "EITP_SEC_AUDIT_TAMPER_ATTEMPT"
    SKIP_REASON_REQUIRED = "EITP_SEC_SKIP_REASON_REQUIRED"
    MODULE_SKIP_FORBIDDEN = "EITP_SEC_MODULE_SKIP_FORBIDDEN"
    CROSS_TENANT_ACCESS_BLOCKED = "EITP_SEC_CROSS_TENANT_ACCESS_BLOCKED"
    CROSS_TENANT_REF_BLOCKED = "EITP_SEC_CROSS_TENANT_REF_BLOCKED"
    CROSS_TENANT_REF_LEAK = "EITP_SEC_CROSS_TENANT_REF_LEAK"
    E2E_LEAK_AT_STEP = "EITP_SEC_E2E_LEAK_AT_STEP"
    E2E_STEP_UNEXECUTABLE = "EITP_SEC_E2E_STEP_UNEXECUTABLE"
    E2E_EVIDENCE_MISSING = "EITP_SEC_E2E_EVIDENCE_MISSING"
    AGGREGATE_LEAK = "EITP_SEC_AGGREGATE_LEAK"
    AUDIT_LEAK = "EITP_SEC_AUDIT_LEAK"
    EXPORT_LEAK = "EITP_SEC_EXPORT_LEAK"
    CACHE_LEAK = "EITP_SEC_CACHE_LEAK"
    ASYNC_JOB_CROSS_TENANT = "EITP_SEC_ASYNC_JOB_CROSS_TENANT"
    SERVICE_UNAVAILABLE = "EITP_SEC_SERVICE_UNAVAILABLE"


class RELErrorCode(str, Enum):
    """EITP REL 错误码枚举 - 全部以 EITP_REL_ 前缀。"""

    GATE_MILESTONE_NOT_PASS = "EITP_REL_GATE_MILESTONE_NOT_PASS"
    GATE_CORE_TAMPERED = "EITP_REL_GATE_CORE_TAMPERED"
    GATE_REGRESSION_FAILED = "EITP_REL_GATE_REGRESSION_FAILED"
    GATE_DIRTY_WORKTREE = "EITP_REL_GATE_DIRTY_WORKTREE"
    GATE_TAG_EXISTS = "EITP_REL_GATE_TAG_EXISTS"
    GATE_CERT_INVALID = "EITP_REL_GATE_CERT_INVALID"
    GATE_BYPASS_FORBIDDEN = "EITP_REL_GATE_BYPASS_FORBIDDEN"
    TAG_NOT_ANNOTATED = "EITP_REL_TAG_NOT_ANNOTATED"
    TAG_DELETE_FORBIDDEN = "EITP_REL_TAG_DELETE_FORBIDDEN"
    TAG_MOVE_FORBIDDEN = "EITP_REL_TAG_MOVE_FORBIDDEN"
    TAG_INCOMPLETE_TREE = "EITP_REL_TAG_INCOMPLETE_TREE"
    TAG_TREE_CHANGED = "EITP_REL_TAG_TREE_CHANGED"
    TAG_PUSH_FAILED = "EITP_REL_TAG_PUSH_FAILED"
    TAG_HOOK_MISSING = "EITP_REL_TAG_HOOK_MISSING"
    MIGRATION_CHAIN_BROKEN = "EITP_REL_MIGRATION_CHAIN_BROKEN"
    DDL_INCOMPLETE = "EITP_REL_DDL_INCOMPLETE"
    MIGRATION_FROZEN_MODIFIED = "EITP_REL_MIGRATION_FROZEN_MODIFIED"
    DDL_EXPORT_FAILED = "EITP_REL_DDL_EXPORT_FAILED"
    DDL_MIGRATION_MISMATCH = "EITP_REL_DDL_MIGRATION_MISMATCH"
    OPENAPI_ENDPOINT_MISSING = "EITP_REL_OPENAPI_ENDPOINT_MISSING"
    OPENAPI_CONTRACT_FROZEN_MODIFIED = "EITP_REL_OPENAPI_CONTRACT_FROZEN_MODIFIED"
    PERMISSION_FROZEN_MODIFIED = "EITP_REL_PERMISSION_FROZEN_MODIFIED"
    RLS_FROZEN_MODIFIED = "EITP_REL_RLS_FROZEN_MODIFIED"
    RLS_NOT_FORCED = "EITP_REL_RLS_NOT_FORCED"
    SEC_CERT_EXPIRED = "EITP_REL_SEC_CERT_EXPIRED"
    SEC_CERT_NOT_FOUND = "EITP_REL_SEC_CERT_NOT_FOUND"
    PROD_DOSSIER_FAIL = "EITP_REL_PROD_DOSSIER_FAIL"
    PROD_DOSSIER_NOT_SIGNED = "EITP_REL_PROD_DOSSIER_NOT_SIGNED"
    TEST_RESULT_HAS_FAILURE = "EITP_REL_TEST_RESULT_HAS_FAILURE"
    TEST_RESULT_NOT_FOUND = "EITP_REL_TEST_RESULT_NOT_FOUND"
    PERF_BASELINE_DEGRADED = "EITP_REL_PERF_BASELINE_DEGRADED"
    PERF_BASELINE_NOT_FOUND = "EITP_REL_PERF_BASELINE_NOT_FOUND"
    IMAGE_FLOATING_TAG = "EITP_REL_IMAGE_FLOATING_TAG"
    IMAGE_NOT_LOCKED = "EITP_REL_IMAGE_NOT_LOCKED"
    IMAGE_PUSH_FAILED = "EITP_REL_IMAGE_PUSH_FAILED"
    CONFIG_BASELINE_DRIFT = "EITP_REL_CONFIG_BASELINE_DRIFT"
    CONFIG_EXPORT_FAILED = "EITP_REL_CONFIG_EXPORT_FAILED"
    BACKUP_EVIDENCE_NOT_FOUND = "EITP_REL_BACKUP_EVIDENCE_NOT_FOUND"
    BACKUP_EVIDENCE_TAMPERED = "EITP_REL_BACKUP_EVIDENCE_TAMPERED"
    DR_EVIDENCE_NOT_FOUND = "EITP_REL_DR_EVIDENCE_NOT_FOUND"
    DR_EVIDENCE_TAMPERED = "EITP_REL_DR_EVIDENCE_TAMPERED"
    ROLLBACK_MIGRATION_NOT_INVERSE = "EITP_REL_ROLLBACK_MIGRATION_NOT_INVERSE"
    ROLLBACK_DRILL_FAILED = "EITP_REL_ROLLBACK_DRILL_FAILED"
    ROLLBACK_PLAN_NOT_FOUND = "EITP_REL_ROLLBACK_PLAN_NOT_FOUND"
    FREEZE_DECLARATION_MISSING = "EITP_REL_FREEZE_DECLARATION_MISSING"
    FREEZE_DECLARATION_ALREADY_EFFECTIVE = "EITP_REL_FREEZE_DECLARATION_ALREADY_EFFECTIVE"
    FREEZE_DECLARATION_REVOKED = "EITP_REL_FREEZE_DECLARATION_REVOKED"
    SEAL_NOT_CO_SIGNED = "EITP_REL_SEAL_NOT_CO_SIGNED"
    SEAL_FAIL = "EITP_REL_SEAL_FAIL"
    SEAL_AUDIT_INVALID = "EITP_REL_SEAL_AUDIT_INVALID"
    SEAL_ALREADY_EXISTS = "EITP_REL_SEAL_ALREADY_EXISTS"
    SEAL_NOT_FOUND = "EITP_REL_SEAL_NOT_FOUND"
    SEAL_INVALID_STATE_TRANSITION = "EITP_REL_SEAL_INVALID_STATE_TRANSITION"
    ASSET_SNAPSHOT_TAMPERED = "EITP_REL_ASSET_SNAPSHOT_TAMPERED"
    ASSET_SNAPSHOT_NOT_FOUND = "EITP_REL_ASSET_SNAPSHOT_NOT_FOUND"
    ASSET_SNAPSHOT_COLLECTION_TIMEOUT = "EITP_REL_ASSET_SNAPSHOT_COLLECTION_TIMEOUT"
    ASSET_SNAPSHOT_ARCHIVE_FAILED = "EITP_REL_ASSET_SNAPSHOT_ARCHIVE_FAILED"
    CO_SIGN_UNAUTHORIZED_RELEASER = "EITP_REL_CO_SIGN_UNAUTHORIZED_RELEASER"
    CO_SIGN_UNAUTHORIZED_SECURITY = "EITP_REL_CO_SIGN_UNAUTHORIZED_SECURITY"
    CO_SIGN_ALREADY_SIGNED = "EITP_REL_CO_SIGN_ALREADY_SIGNED"
    UNFREEZE_NOT_APPROVED = "EITP_REL_UNFREEZE_NOT_APPROVED"
    UNFREEZE_FORBIDDEN = "EITP_REL_UNFREEZE_FORBIDDEN"
    INTERNAL_ERROR = "EITP_REL_INTERNAL_ERROR"


AnyErrorCode = Union[ErrorCode, IAMErrorCode, INVErrorCode, MDMErrorCode, WMSErrorCode, PURErrorCode, SALErrorCode, SECErrorCode, PLTErrorCode, PRODErrorCode, RELErrorCode]


class DomainError(Exception):
    """领域错误基类。"""

    def __init__(self, code: AnyErrorCode, message: str, details: dict | None = None) -> None:
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(message)


class IAMError(DomainError):
    """IAM 领域错误。"""
    pass


class INVError(DomainError):
    """INV 领域错误。"""
    pass


class MDMError(DomainError):
    """MDM 领域错误。"""
    pass


class WMSError(DomainError):
    """WMS 领域错误。"""
    pass


class PURError(DomainError):
    """PUR 领域错误。"""
    pass


class SALError(DomainError):
    """SAL 领域错误。"""
    pass


class SECError(DomainError):
    """SEC 领域错误。"""
    pass


class PLTError(DomainError):
    """PLT 领域错误。"""
    pass


class PRODError(DomainError):
    """PROD 领域错误。"""
    pass


class RELError(DomainError):
    """REL 领域错误。"""
    pass


class TenantContextError(DomainError):
    def __init__(self, message: str = "租户上下文无效或缺失") -> None:
        super().__init__(ErrorCode.TENANT_CONTEXT_INVALID, message)


class HierarchyError(DomainError):
    pass


class ConfigError(DomainError):
    pass


class GroupError(DomainError):
    pass


def setup_exception_handlers(app: FastAPI) -> None:
    """注册全局异常处理器。"""

    @app.exception_handler(DomainError)
    async def domain_error_handler(request: Request, exc: DomainError) -> JSONResponse:
        logger.warning(
            "domain_error",
            error_code=exc.code.value,
            message=exc.message,
            path=request.url.path,
            trace_id=getattr(request.state, "trace_id", None),
        )
        status = _status_for_code(exc.code)
        return JSONResponse(
            status_code=status,
            content={
                "error_code": exc.code.value,
                "message": exc.message,
                "details": exc.details,
            },
        )

    @app.exception_handler(Exception)
    async def unhandled_error_handler(request: Request, exc: Exception) -> JSONResponse:
        logger.exception(
            "unhandled_error",
            path=request.url.path,
            trace_id=getattr(request.state, "trace_id", None),
        )
        return JSONResponse(
            status_code=500,
            content={
                "error_code": "EITP_MT_INTERNAL_ERROR",
                "message": "内部服务器错误",
            },
        )


def _status_for_code(code: AnyErrorCode) -> int:
    if isinstance(code, RELErrorCode):
        return _status_for_rel_code(code)
    if isinstance(code, PRODErrorCode):
        return _status_for_prod_code(code)
    if isinstance(code, PLTErrorCode):
        return _status_for_plt_code(code)
    if isinstance(code, SECErrorCode):
        return _status_for_sec_code(code)
    if isinstance(code, SALErrorCode):
        return _status_for_sal_code(code)
    if isinstance(code, PURErrorCode):
        return _status_for_pur_code(code)
    if isinstance(code, WMSErrorCode):
        return _status_for_wms_code(code)
    if isinstance(code, MDMErrorCode):
        return _status_for_mdm_code(code)
    if isinstance(code, INVErrorCode):
        return _status_for_inv_code(code)
    if isinstance(code, IAMErrorCode):
        return _status_for_iam_code(code)
    if code in {ErrorCode.TENANT_CONTEXT_INVALID, ErrorCode.CROSS_TENANT_REF_DENIED}:
        return 401 if code == ErrorCode.TENANT_CONTEXT_INVALID else 403
    if code == ErrorCode.TENANT_ALREADY_EXISTS:
        return 409
    if code in {
        ErrorCode.HIERARCHY_DEPTH_EXCEEDED,
        ErrorCode.HIERARCHY_CROSS_TENANT,
        ErrorCode.HIERARCHY_CIRCULAR_REF,
        ErrorCode.HIERARCHY_HAS_ACTIVE_DATA,
        ErrorCode.CONFIG_INVALID,
        ErrorCode.CONFIG_INHERIT_CONFLICT,
        ErrorCode.FEATURE_HAS_ACTIVE_DATA,
        ErrorCode.WORKFLOW_INCOMPLETE,
        ErrorCode.DEPROVISION_REQUIRES_DISABLE,
        ErrorCode.MASTER_DATA_CONFLICT,
        ErrorCode.MASTER_PROPAGATE_FAILED,
        ErrorCode.SUBSIDIARY_ISOLATION_VIOLATION,
        ErrorCode.MASTER_BASE_READONLY,
        ErrorCode.MASTER_ATTR_CONFLICT,
        ErrorCode.MASTER_NOT_FOUND,
        ErrorCode.MIGRATION_VERIFY_FAILED,
        ErrorCode.MIGRATION_TIMEOUT,
        ErrorCode.PLACEMENT_RESOURCE_INSUFFICIENT,
    }:
        return 422
    if code == ErrorCode.DEPROVISION_CONFIRM_REQUIRED:
        return 400
    if code == ErrorCode.GROUP_READONLY_VIOLATION:
        return 403
    if code == ErrorCode.CROSS_TENANT_RESTORE_DENIED:
        return 403
    if code == ErrorCode.GROUP_SNAPSHOT_DELAYED:
        return 200
    return 400


def _status_for_iam_code(code: IAMErrorCode) -> int:
    _401_CODES = {
        IAMErrorCode.CREDENTIAL_INVALID,
        IAMErrorCode.TOKEN_EXPIRED,
        IAMErrorCode.TOKEN_REVOKED,
        IAMErrorCode.TOKEN_SIGNATURE_INVALID,
        IAMErrorCode.TOKEN_MISSING,
        IAMErrorCode.REFRESH_TOKEN_REVOKED,
        IAMErrorCode.SESSION_EXPIRED,
        IAMErrorCode.TENANT_TOKEN_MISSING,
    }
    _403_CODES = {
        IAMErrorCode.ACCOUNT_LOCKED,
        IAMErrorCode.IP_BANNED,
        IAMErrorCode.TENANT_DISABLED,
        IAMErrorCode.TENANT_MISMATCH,
        IAMErrorCode.PERMISSION_DENIED,
        IAMErrorCode.CROSS_TENANT_ROLE_DENIED,
        IAMErrorCode.CROSS_TENANT_REF_DENIED,
        IAMErrorCode.CROSS_TENANT_DATASCOPE_DENIED,
        IAMErrorCode.CROSS_TENANT_AUDIT_DENIED,
        IAMErrorCode.BUILTIN_ROLE_PROTECTED,
        IAMErrorCode.ROLE_HIERARCHY_VIOLATION,
        IAMErrorCode.TENANT_NOT_AUTHORIZED,
        IAMErrorCode.ENTERPRISE_SCOPE_EXCEEDED,
        IAMErrorCode.TENANT_CONTEXT_MISMATCH,
    }
    _409_CODES = {
        IAMErrorCode.USER_DUPLICATE,
        IAMErrorCode.ROLE_DUPLICATE,
    }
    _422_CODES = {
        IAMErrorCode.PASSWORD_WEAK,
        IAMErrorCode.PASSWORD_REUSE_DENIED,
        IAMErrorCode.PASSWORD_POLICY_BELOW_PLATFORM,
        IAMErrorCode.OLD_PASSWORD_INVALID,
        IAMErrorCode.DATASCOPE_UNRESOLVABLE,
        IAMErrorCode.PERMISSION_MAPPING_MISSING,
    }
    _400_CODES = {
        IAMErrorCode.PERMISSION_NOT_FOUND,
        IAMErrorCode.USER_NOT_FOUND,
        IAMErrorCode.DEPT_HAS_ACTIVE_USERS,
        IAMErrorCode.DEACTIVATE_CONFIRM_REQUIRED,
        IAMErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _401_CODES:
        return 401
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _400_CODES:
        return 400
    return 400


def _status_for_inv_code(code: INVErrorCode) -> int:
    _404_CODES = {
        INVErrorCode.SKU_NOT_FOUND,
        INVErrorCode.PRODUCT_NOT_FOUND,
        INVErrorCode.WAREHOUSE_NOT_FOUND,
        INVErrorCode.LOCATION_NOT_FOUND,
        INVErrorCode.BALANCE_NOT_FOUND,
        INVErrorCode.DOCUMENT_NOT_FOUND,
        INVErrorCode.RESERVATION_NOT_FOUND,
    }
    _403_CODES = {
        INVErrorCode.CROSS_TENANT_REF_DENIED,
        INVErrorCode.CROSS_TENANT_AUDIT_DENIED,
        INVErrorCode.NEGATIVE_STOCK_FORCE_DENIED,
        INVErrorCode.STATE_TRANSITION_DENIED,
        INVErrorCode.STOCK_BLOCKED_BY_COUNT,
        INVErrorCode.DOCUMENT_NOT_EDITABLE,
        INVErrorCode.DOCUMENT_NOT_DELETABLE,
    }
    _409_CODES = {
        INVErrorCode.SKU_DUPLICATE,
        INVErrorCode.PRODUCT_DUPLICATE,
        INVErrorCode.CATEGORY_DUPLICATE,
        INVErrorCode.IDEMPOTENCY_KEY_CONFLICT,
        INVErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        INVErrorCode.UNIT_CONVERSION_CONFLICT,
        INVErrorCode.COST_MODEL_SWITCH_CONFLICT,
        INVErrorCode.RESERVATION_ALREADY_RELEASED,
    }
    _422_CODES = {
        INVErrorCode.PRODUCT_HAS_ACTIVE_DOCUMENT,
        INVErrorCode.WAREHOUSE_DISABLED,
        INVErrorCode.LOCATION_CAPACITY_EXCEEDED,
        INVErrorCode.LEDGER_FIELD_REQUIRED,
        INVErrorCode.LEDGER_APPEND_FAILED,
        INVErrorCode.LEDGER_QUERY_RANGE_EXCEEDED,
        INVErrorCode.BALANCE_SNAPSHOT_INCONSISTENT,
        INVErrorCode.INSUFFICIENT_STOCK,
        INVErrorCode.INSUFFICIENT_AVAILABLE,
        INVErrorCode.INVALID_STATE_TRANSITION,
        INVErrorCode.OWNERSHIP_REQUIRED,
        INVErrorCode.COST_MODEL_NOT_CONFIGURED,
        INVErrorCode.COUNT_DIFF_EXCEEDED_THRESHOLD,
        INVErrorCode.ADJUST_EXCEED_ONHAND,
        INVErrorCode.BLOCK_EXCEED_ONHAND,
        INVErrorCode.BATCH_SIZE_EXCEEDED,
        INVErrorCode.RESERVATION_EXPIRED,
    }
    _408_CODES = {
        INVErrorCode.NEGATIVE_STOCK_APPROVAL_TIMEOUT,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _408_CODES:
        return 408
    return 400


def _status_for_mdm_code(code: MDMErrorCode) -> int:
    _404_CODES = {
        MDMErrorCode.VERSION_NOT_FOUND,
        MDMErrorCode.GROUP_PRODUCT_NOT_PUBLISHED,
    }
    _403_CODES = {
        MDMErrorCode.CROSS_ENTERPRISE_REF_DENIED,
        MDMErrorCode.GROUP_BASE_ATTRIBUTE_READONLY,
        MDMErrorCode.CATEGORY_MULTI_BELONG_DENIED,
        MDMErrorCode.GROUP_CATEGORY_PERMISSION_DENIED,
        MDMErrorCode.GROUP_UNIT_PERMISSION_DENIED,
        MDMErrorCode.GOVERNANCE_APPROVAL_DENIED,
        MDMErrorCode.CROSS_LEVEL_GOVERNANCE_DENIED,
        MDMErrorCode.GROUP_PRODUCT_HAS_ACTIVE_REFERENCE,
        MDMErrorCode.REFERENCE_HAS_ACTIVE_DOCUMENT,
        MDMErrorCode.NEGATIVE_POLICY_PERMISSION_DENIED,
        MDMErrorCode.CROSS_TENANT_POLICY_DENIED,
        MDMErrorCode.NEGATIVE_POLICY_DEFAULT_MUST_STRICT,
        MDMErrorCode.LEDGER_TRIGGER_GUARD_FAILED,
        MDMErrorCode.IDEMPOTENCY_FAIL_SAFE_VIOLATION,
        MDMErrorCode.INV_REGRESSION_FAILED,
        MDMErrorCode.PRODUCT_NOT_AVAILABLE,
        MDMErrorCode.DIRECT_ACCESS_DENIED,
        MDMErrorCode.GROUP_CATALOG_PERMISSION_DENIED,
        MDMErrorCode.GROUP_PRODUCT_DISABLED,
    }
    _409_CODES = {
        MDMErrorCode.GROUP_SKU_DUPLICATE,
        MDMErrorCode.DUPLICATE_REFERENCE,
        MDMErrorCode.BARCODE_DUPLICATE,
    }
    _422_CODES = {
        MDMErrorCode.SPEC_INSTANCE_INVALID,
        MDMErrorCode.ATTRIBUTE_INSTANCE_INVALID,
        MDMErrorCode.SPEC_TEMPLATE_CYCLE,
        MDMErrorCode.CATEGORY_CYCLE,
        MDMErrorCode.UNIT_CONVERSION_CONFLICT,
        MDMErrorCode.INVALID_GOVERNANCE_STATE_TRANSITION,
        MDMErrorCode.GOVERNANCE_REQUEST_NOT_EDITABLE,
        MDMErrorCode.NEGATIVE_POLICY_REASON_REQUIRED,
    }
    _500_CODES = {
        MDMErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    return 400


def _status_for_sec_code(code: SECErrorCode) -> int:
    _401_CODES = {
        SECErrorCode.JWT_TENANT_MISMATCH,
        SECErrorCode.TENANT_TOKEN_JWT_INCONSISTENT,
        SECErrorCode.CONTEXT_INCONSISTENT,
    }
    _403_CODES = {
        SECErrorCode.DATASCOPE_VIOLATION,
        SECErrorCode.API_CROSS_TENANT_ACCESS,
        SECErrorCode.APP_CROSS_TENANT_COMMAND,
        SECErrorCode.REPO_MISSING_TENANT_FILTER,
        SECErrorCode.JOIN_CROSS_TENANT_LEAK,
        SECErrorCode.JOIN_MISSING_TENANT_FILTER,
        SECErrorCode.JOIN_TENANT_ID_INCONSISTENT,
        SECErrorCode.AGGREGATE_REVERSIBLE,
        SECErrorCode.REDIS_KEY_VIOLATION,
        SECErrorCode.REDIS_KEY_PREFIX_MISSING,
        SECErrorCode.PLATFORM_ADMIN_BUSINESS_DATA_DENIED,
        SECErrorCode.PLATFORM_ADMIN_BUSINESS_WRITE_DENIED,
        SECErrorCode.APPLICATION_NOT_AUDITED,
        SECErrorCode.CERT_REVOKED_USED,
        SECErrorCode.REPORT_ACCESS_DENIED,
        SECErrorCode.AUDIT_TAMPER_ATTEMPT,
        SECErrorCode.MODULE_SKIP_FORBIDDEN,
        SECErrorCode.CROSS_TENANT_ACCESS_BLOCKED,
        SECErrorCode.CROSS_TENANT_REF_BLOCKED,
        SECErrorCode.CROSS_TENANT_REF_LEAK,
        SECErrorCode.AGGREGATE_LEAK,
        SECErrorCode.AUDIT_LEAK,
        SECErrorCode.EXPORT_LEAK,
        SECErrorCode.CACHE_LEAK,
        SECErrorCode.ASYNC_JOB_CROSS_TENANT,
    }
    _404_CODES = {
        SECErrorCode.REPORT_NOT_FOUND,
        SECErrorCode.EVIDENCE_MISSING,
    }
    _409_CODES = {
        SECErrorCode.CERT_ALREADY_RUNNING,
    }
    _422_CODES = {
        SECErrorCode.CERT_PREREQUISITE_NOT_MET,
        SECErrorCode.CERT_ITEM_TIMEOUT,
        SECErrorCode.MATRIX_CONFIG_INVALID,
        SECErrorCode.SKIP_REASON_REQUIRED,
        SECErrorCode.E2E_LEAK_AT_STEP,
        SECErrorCode.E2E_STEP_UNEXECUTABLE,
        SECErrorCode.E2E_EVIDENCE_MISSING,
    }
    _500_CODES = {
        SECErrorCode.CERT_ISSUE_FAILED,
        SECErrorCode.CERT_SIGN_FAILED,
        SECErrorCode.CERT_PERSIST_FAILED,
        SECErrorCode.REPORT_PERSIST_FAILED,
        SECErrorCode.REDIS_UNREACHABLE,
        SECErrorCode.REDIS_SCAN_TIMEOUT,
        SECErrorCode.REDIS_KEY_CLEANUP_FAILED,
        SECErrorCode.ATTACK_VECTOR_SETUP_FAILED,
        SECErrorCode.TEST_TENANT_SETUP_FAILED,
        SECErrorCode.TEST_DATA_CLEANUP_FAILED,
        SECErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _401_CODES:
        return 401
    if code in _403_CODES:
        return 403
    if code in _404_CODES:
        return 404
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    return 400


def _status_for_sal_code(code: SALErrorCode) -> int:
    _404_CODES = {
        SALErrorCode.CUSTOMER_NOT_FOUND,
        SALErrorCode.QUOTATION_NOT_FOUND,
        SALErrorCode.ORDER_NOT_FOUND,
        SALErrorCode.SHIPMENT_NOT_FOUND,
        SALErrorCode.RETURN_NOT_FOUND,
        SALErrorCode.SETTLEMENT_NOT_FOUND,
        SALErrorCode.INVOICE_NOT_FOUND,
        SALErrorCode.PAYMENT_NOT_FOUND,
        SALErrorCode.SKU_NOT_FOUND,
        SALErrorCode.PRICING_NOT_FOUND,
        SALErrorCode.CREDIT_CONFIG_NOT_FOUND,
    }
    _403_CODES = {
        SALErrorCode.CUSTOMER_DISABLED,
        SALErrorCode.CUSTOMER_NOT_ACTIVE,
        SALErrorCode.CROSS_TENANT_CUSTOMER_DENIED,
        SALErrorCode.CROSS_TENANT_REF_DENIED,
        SALErrorCode.DIRECT_INVENTORY_MODIFY_DENIED,
        SALErrorCode.DIRECT_REVENUE_MODIFY_DENIED,
        SALErrorCode.DIRECT_RESERVATION_MODIFY_DENIED,
        SALErrorCode.QUOTATION_NOT_APPROVED,
        SALErrorCode.ORDER_NOT_APPROVED,
        SALErrorCode.RETURN_NOT_APPROVED,
        SALErrorCode.OWNERSHIP_REQUIRED,
        SALErrorCode.PORTAL_PERMISSION_DENIED,
    }
    _409_CODES = {
        SALErrorCode.CUSTOMER_CODE_DUPLICATE,
        SALErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        SALErrorCode.CREDIT_CONCURRENT_CONFLICT,
    }
    _422_CODES = {
        SALErrorCode.CREDIT_LIMIT_EXCEEDED,
        SALErrorCode.QUOTATION_EXPIRED,
        SALErrorCode.QUOTATION_INVALID_STATE_TRANSITION,
        SALErrorCode.SKU_DISABLED,
        SALErrorCode.ORDER_INVALID_STATE_TRANSITION,
        SALErrorCode.ORDER_CANCEL_WITH_SHIPPED,
        SALErrorCode.RESERVATION_FAILED,
        SALErrorCode.INSUFFICIENT_STOCK,
        SALErrorCode.SHIPMENT_OVER_SHIPPED,
        SALErrorCode.SHIPMENT_ORDER_INVALID,
        SALErrorCode.RETURN_OVER_RETURNED,
        SALErrorCode.SETTLEMENT_RECONCILE_DIFF_EXCEEDED,
        SALErrorCode.INVOICE_MATCH_DIFF_EXCEEDED,
        SALErrorCode.WMS_INV_INCONSISTENT,
        SALErrorCode.APPROVAL_TIMEOUT,
        SALErrorCode.PROMOTION_INVALID,
        SALErrorCode.CONTRACT_QTY_EXCEEDED,
    }
    _500_CODES = {
        SALErrorCode.WMS_PICKING_FAILED,
        SALErrorCode.WMS_SHIPPING_FAILED,
        SALErrorCode.RETURN_RECEIVING_FAILED,
        SALErrorCode.FINANCIAL_API_FAILED,
        SALErrorCode.PAYMENT_FAILED,
        SALErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    return 400


def _status_for_wms_code(code: WMSErrorCode) -> int:
    _404_CODES = {
        WMSErrorCode.LOCATION_NOT_FOUND,
        WMSErrorCode.ZONE_NOT_FOUND,
        WMSErrorCode.AREA_NOT_FOUND,
        WMSErrorCode.RECEIVING_NOT_FOUND,
        WMSErrorCode.PUTAWAY_NOT_FOUND,
        WMSErrorCode.PICKING_NOT_FOUND,
        WMSErrorCode.TRANSFER_NOT_FOUND,
        WMSErrorCode.SHIPPING_NOT_FOUND,
        WMSErrorCode.TASK_NOT_FOUND,
        WMSErrorCode.SKU_NOT_FOUND,
        WMSErrorCode.WAREHOUSE_NOT_FOUND,
    }
    _403_CODES = {
        WMSErrorCode.LOCATION_DISABLED,
        WMSErrorCode.DIRECT_POSITION_MODIFY_DENIED,
        WMSErrorCode.PUTAWAY_LOCATION_DISABLED,
        WMSErrorCode.PICKING_STATUS_UNAVAILABLE,
        WMSErrorCode.SHIPPING_PICKING_NOT_COMPLETED,
        WMSErrorCode.TASK_ASSIGNMENT_DENIED,
        WMSErrorCode.DIRECT_INVENTORY_MODIFY_DENIED,
        WMSErrorCode.CROSS_TENANT_REF_DENIED,
        WMSErrorCode.WAREHOUSE_DISABLED,
        WMSErrorCode.OWNERSHIP_REQUIRED,
    }
    _409_CODES = {
        WMSErrorCode.LOCATION_CODE_DUPLICATE,
        WMSErrorCode.IDEMPOTENCY_KEY_CONFLICT,
        WMSErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        WMSErrorCode.RECEIVING_ALREADY_COMPLETED,
        WMSErrorCode.PUTAWAY_ALREADY_COMPLETED,
        WMSErrorCode.PICKING_ALREADY_COMPLETED,
        WMSErrorCode.SHIPPING_ALREADY_COMPLETED,
        WMSErrorCode.TASK_ALREADY_COMPLETED,
    }
    _422_CODES = {
        WMSErrorCode.LOCATION_CAPACITY_EXCEEDED,
        WMSErrorCode.ZONE_FUNCTION_MISMATCH,
        WMSErrorCode.HIERARCHY_CYCLE,
        WMSErrorCode.INV_INCONSISTENT,
        WMSErrorCode.RECEIVING_OVER_RECEIVED,
        WMSErrorCode.RECEIVING_ZONE_INVALID,
        WMSErrorCode.PUTAWAY_CAPACITY_EXCEEDED,
        WMSErrorCode.PUTAWAY_ZONE_NOT_STORAGE,
        WMSErrorCode.PICKING_INSUFFICIENT_AVAILABLE,
        WMSErrorCode.PICKING_QTY_MISMATCH,
        WMSErrorCode.TRANSFER_CROSS_WAREHOUSE,
        WMSErrorCode.TRANSFER_INSUFFICIENT_SOURCE,
        WMSErrorCode.TRANSFER_TARGET_CAPACITY_EXCEEDED,
        WMSErrorCode.SHIPPING_ZONE_INVALID,
        WMSErrorCode.TASK_INVALID_STATE_TRANSITION,
        WMSErrorCode.INV_TRANSACTION_FAILED,
        WMSErrorCode.BATCH_REQUIRED,
    }
    _500_CODES = {
        WMSErrorCode.SERVICE_UNAVAILABLE,
    }
    _200_CODES = {
        WMSErrorCode.EXPIRY_WARNING,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    if code in _200_CODES:
        return 200
    return 400


def _status_for_pur_code(code: PURErrorCode) -> int:
    _404_CODES = {
        PURErrorCode.SUPPLIER_NOT_FOUND,
        PURErrorCode.REQUEST_NOT_FOUND,
        PURErrorCode.ORDER_NOT_FOUND,
        PURErrorCode.ORDER_LINE_NOT_FOUND,
        PURErrorCode.RECEIPT_NOT_FOUND,
        PURErrorCode.RETURN_NOT_FOUND,
        PURErrorCode.SETTLEMENT_NOT_FOUND,
        PURErrorCode.INVOICE_NOT_FOUND,
        PURErrorCode.PAYMENT_NOT_FOUND,
        PURErrorCode.ASN_NOT_FOUND,
        PURErrorCode.QUOTATION_NOT_FOUND,
        PURErrorCode.EVALUATION_NOT_FOUND,
        PURErrorCode.SKU_NOT_FOUND,
        PURErrorCode.BUDGET_NOT_FOUND,
    }
    _403_CODES = {
        PURErrorCode.SUPPLIER_DISABLED,
        PURErrorCode.SUPPLIER_NOT_ACTIVE,
        PURErrorCode.CROSS_TENANT_SUPPLIER_DENIED,
        PURErrorCode.CROSS_TENANT_REF_DENIED,
        PURErrorCode.DIRECT_INVENTORY_MODIFY_DENIED,
        PURErrorCode.DIRECT_COST_MODIFY_DENIED,
        PURErrorCode.REQUEST_NOT_APPROVED,
        PURErrorCode.ORDER_NOT_APPROVED,
        PURErrorCode.RETURN_NOT_APPROVED,
        PURErrorCode.OWNERSHIP_REQUIRED,
        PURErrorCode.PORTAL_PERMISSION_DENIED,
    }
    _409_CODES = {
        PURErrorCode.SUPPLIER_CODE_DUPLICATE,
        PURErrorCode.IDEMPOTENCY_KEY_CONFLICT,
        PURErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        PURErrorCode.PAYMENT_ALREADY_COMPLETED,
    }
    _422_CODES = {
        PURErrorCode.SUPPLIER_SCOPE_MISMATCH,
        PURErrorCode.REQUEST_BUDGET_EXCEEDED,
        PURErrorCode.SKU_DISABLED,
        PURErrorCode.ORDER_INVALID_STATE_TRANSITION,
        PURErrorCode.ORDER_CANCEL_WITH_RECEIVED,
        PURErrorCode.RECEIPT_OVER_RECEIVED,
        PURErrorCode.RECEIPT_ORDER_INVALID,
        PURErrorCode.RETURN_OVER_RETURNED,
        PURErrorCode.SETTLEMENT_RECONCILE_DIFF_EXCEEDED,
        PURErrorCode.INVOICE_MATCH_DIFF_EXCEEDED,
        PURErrorCode.WMS_INV_INCONSISTENT,
        PURErrorCode.RMQ_INVALID_STATE_TRANSITION,
        PURErrorCode.FRAMEWORK_AGREEMENT_EXPIRED,
        PURErrorCode.FRAMEWORK_AGREEMENT_QTY_EXCEEDED,
        PURErrorCode.APPROVAL_TIMEOUT,
    }
    _500_CODES = {
        PURErrorCode.WMS_RECEIVING_FAILED,
        PURErrorCode.RETURN_INVENTORY_FAILED,
        PURErrorCode.FINANCIAL_API_FAILED,
        PURErrorCode.SERVICE_UNAVAILABLE,
    }
    if code in _404_CODES:
        return 404
    if code in _403_CODES:
        return 403
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _500_CODES:
        return 500
    return 400


def _status_for_plt_code(code: PLTErrorCode) -> int:
    _403_CODES = {
        PLTErrorCode.AUDIT_CROSS_TENANT_DENIED,
        PLTErrorCode.AUDIT_EXPORT_DENIED,
        PLTErrorCode.ROLE_PERMISSION_DENIED,
        PLTErrorCode.DB_RLS_VIOLATION,
    }
    _404_CODES = {
        PLTErrorCode.AUDIT_NOT_FOUND,
        PLTErrorCode.OUTBOX_EVENT_NOT_FOUND,
        PLTErrorCode.SAGA_NOT_FOUND,
        PLTErrorCode.PERMISSION_NOT_FOUND,
        PLTErrorCode.TENANT_NOT_FOUND,
        PLTErrorCode.CONFIG_NOT_FOUND,
        PLTErrorCode.API_CONTRACT_NOT_FOUND,
        PLTErrorCode.JOB_NOT_FOUND,
        PLTErrorCode.PERFORMANCE_BASELINE_NOT_FOUND,
        PLTErrorCode.OBSERVABILITY_TRACE_NOT_FOUND,
    }
    _405_CODES = {
        PLTErrorCode.AUDIT_UPDATE_FORBIDDEN,
        PLTErrorCode.AUDIT_DELETE_FORBIDDEN,
    }
    _409_CODES = {
        PLTErrorCode.IDEMPOTENCY_CONFLICT,
        PLTErrorCode.IDEMPOTENCY_KEY_FORMAT_VIOLATION,
        PLTErrorCode.IDEMPOTENCY_KEY_REQUIRED,
        PLTErrorCode.PERMISSION_MATRIX_CONFLICT,
        PLTErrorCode.PERMISSION_APPROVER_CONFLICT,
        PLTErrorCode.CONFIG_VERSION_CONFLICT,
        PLTErrorCode.JOB_CONFLICT,
        PLTErrorCode.ROLE_MIGRATION_CONFLICT,
        PLTErrorCode.ERRORCODE_DUPLICATE,
    }
    _410_CODES = {
        PLTErrorCode.API_VERSION_SUNSET,
    }
    _422_CODES = {
        PLTErrorCode.AUDIT_RETENTION_INVALID,
        PLTErrorCode.SAGA_INVALID_TRANSITION,
        PLTErrorCode.SAGA_STEP_FAILED,
        PLTErrorCode.TENANT_QUOTA_EXCEEDED,
        PLTErrorCode.TENANT_ARCHIVED,
        PLTErrorCode.TENANT_FROZEN,
        PLTErrorCode.TENANT_INVALID_TRANSITION,
        PLTErrorCode.TENANT_INIT_FAILED,
        PLTErrorCode.CONFIG_VALUE_INVALID,
        PLTErrorCode.CONFIG_GRAY_RELEASE_INVALID,
        PLTErrorCode.PERMISSION_MENU_CYCLE,
        PLTErrorCode.PERMISSION_APPROVAL_REJECTED,
        PLTErrorCode.IDEMPOTENCY_EXPIRED,
        PLTErrorCode.JOB_DISABLED,
        PLTErrorCode.JOB_HANDLER_NOT_FOUND,
        PLTErrorCode.PERFORMANCE_REGRESSION,
    }
    _423_CODES = {
        PLTErrorCode.AUDIT_TAMPER_DETECTED,
        PLTErrorCode.AUDIT_HASH_CHAIN_BROKEN,
        PLTErrorCode.CERT_GATE_NOT_PASSED,
        PLTErrorCode.SAGA_MANUAL_INTERVENTION_REQUIRED,
    }
    _429_CODES = {
        PLTErrorCode.RATE_LIMIT_EXCEEDED,
    }
    _502_CODES = {
        PLTErrorCode.UPSTREAM_UNAVAILABLE,
    }
    _503_CODES = {
        PLTErrorCode.DB_UNAVAILABLE,
        PLTErrorCode.AUDIT_ARCHIVE_FAILED,
        PLTErrorCode.CICD_PIPELINE_FAILED,
        PLTErrorCode.CICD_DEPLOY_ROLLBACK_FAILED,
        PLTErrorCode.HEALTH_CHECK_FAILED,
    }
    _504_CODES = {
        PLTErrorCode.UPSTREAM_TIMEOUT,
        PLTErrorCode.JOB_TIMEOUT,
    }
    _500_CODES = {
        PLTErrorCode.OUTBOX_DELIVERY_FAILED,
        PLTErrorCode.OUTBOX_MAX_ATTEMPTS_EXCEEDED,
        PLTErrorCode.SAGA_COMPENSATION_FAILED,
        PLTErrorCode.CONFIG_DECRYPT_FAILED,
        PLTErrorCode.ERRORCODE_NOT_REGISTERED,
        PLTErrorCode.OBSERVABILITY_METRIC_INVALID,
        PLTErrorCode.INTERNAL_ERROR,
    }
    _400_CODES = {
        PLTErrorCode.OUTBOX_ALREADY_DELIVERED,
        PLTErrorCode.API_VERSION_DEPRECATED,
    }
    if code in _403_CODES:
        return 403
    if code in _404_CODES:
        return 404
    if code in _405_CODES:
        return 405
    if code in _409_CODES:
        return 409
    if code in _410_CODES:
        return 410
    if code in _422_CODES:
        return 422
    if code in _423_CODES:
        return 423
    if code in _429_CODES:
        return 429
    if code in _502_CODES:
        return 502
    if code in _503_CODES:
        return 503
    if code in _504_CODES:
        return 504
    if code in _500_CODES:
        return 500
    if code in _400_CODES:
        return 400
    return 400


def _status_for_prod_code(code: PRODErrorCode) -> int:
    _403_CODES = {
        PRODErrorCode.CORE_FREEZE_VIOLATED,
        PRODErrorCode.VERIFICATION_ENV_FORBIDDEN,
        PRODErrorCode.DOSSIER_UNAUTHORIZED_SIGNER,
        PRODErrorCode.DR_SINGLE_AUTHORIZATION_DENIED,
    }
    _404_CODES = {
        PRODErrorCode.VERIFICATION_NOT_FOUND,
        PRODErrorCode.DOSSIER_NOT_FOUND,
        PRODErrorCode.EVIDENCE_NOT_FOUND,
    }
    _409_CODES = {
        PRODErrorCode.VERIFICATION_ALREADY_RUNNING,
        PRODErrorCode.DOSSIER_ALREADY_SIGNED,
    }
    _422_CODES = {
        PRODErrorCode.VERIFICATION_PREREQUISITE_NOT_MET,
        PRODErrorCode.BASELINE_INSUFFICIENT_SAMPLES,
        PRODErrorCode.BASELINE_LOW_CONFIDENCE,
        PRODErrorCode.SEC_RECERT_PREREQUISITE_NOT_MET,
        PRODErrorCode.DOSSIER_PREREQUISITE_NOT_MET,
        PRODErrorCode.DOSSIER_EXPIRED,
        PRODErrorCode.DOSSIER_EVIDENCE_MISSING,
    }
    _423_CODES = {
        PRODErrorCode.DOSSIER_EVIDENCE_TAMPERED,
        PRODErrorCode.EVIDENCE_HASH_MISMATCH,
    }
    _500_CODES = {
        PRODErrorCode.CONCURRENT_DATA_INCONSISTENT,
        PRODErrorCode.SAGA_COMPENSATION_INCONSISTENT,
        PRODErrorCode.SAGA_COMPENSATION_NOT_IDEMPOTENT,
        PRODErrorCode.BACKUP_CORRUPTED,
        PRODErrorCode.RESTORE_DATA_MISMATCH,
        PRODErrorCode.DR_DATA_LOSS,
        PRODErrorCode.INTERNAL_ERROR,
    }
    _502_CODES = {
        PRODErrorCode.DR_API_UNAVAILABLE,
    }
    _503_CODES = {
        PRODErrorCode.CONNPOOL_EXHAUSTED_NO_TIMEOUT,
        PRODErrorCode.CACHE_NO_FALLBACK,
        PRODErrorCode.DR_RTO_EXCEEDED,
        PRODErrorCode.CONTAINER_RECOVERY_TIMEOUT,
    }
    _504_CODES = {
        PRODErrorCode.JOB_SCHEDULE_DRIFT,
    }
    if code in _403_CODES:
        return 403
    if code in _404_CODES:
        return 404
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _423_CODES:
        return 423
    if code in _500_CODES:
        return 500
    if code in _502_CODES:
        return 502
    if code in _503_CODES:
        return 503
    if code in _504_CODES:
        return 504
    return 400


def _status_for_rel_code(code: RELErrorCode) -> int:
    _403_CODES = {
        RELErrorCode.GATE_BYPASS_FORBIDDEN,
        RELErrorCode.TAG_DELETE_FORBIDDEN,
        RELErrorCode.TAG_MOVE_FORBIDDEN,
        RELErrorCode.MIGRATION_FROZEN_MODIFIED,
        RELErrorCode.OPENAPI_CONTRACT_FROZEN_MODIFIED,
        RELErrorCode.PERMISSION_FROZEN_MODIFIED,
        RELErrorCode.RLS_FROZEN_MODIFIED,
        RELErrorCode.SEAL_NOT_CO_SIGNED,
        RELErrorCode.CO_SIGN_UNAUTHORIZED_RELEASER,
        RELErrorCode.CO_SIGN_UNAUTHORIZED_SECURITY,
        RELErrorCode.UNFREEZE_FORBIDDEN,
        RELErrorCode.FREEZE_DECLARATION_REVOKED,
    }
    _404_CODES = {
        RELErrorCode.SEC_CERT_NOT_FOUND,
        RELErrorCode.TEST_RESULT_NOT_FOUND,
        RELErrorCode.PERF_BASELINE_NOT_FOUND,
        RELErrorCode.BACKUP_EVIDENCE_NOT_FOUND,
        RELErrorCode.DR_EVIDENCE_NOT_FOUND,
        RELErrorCode.ROLLBACK_PLAN_NOT_FOUND,
        RELErrorCode.SEAL_NOT_FOUND,
        RELErrorCode.ASSET_SNAPSHOT_NOT_FOUND,
        RELErrorCode.FREEZE_DECLARATION_MISSING,
    }
    _409_CODES = {
        RELErrorCode.GATE_TAG_EXISTS,
        RELErrorCode.SEAL_ALREADY_EXISTS,
        RELErrorCode.CO_SIGN_ALREADY_SIGNED,
        RELErrorCode.FREEZE_DECLARATION_ALREADY_EFFECTIVE,
    }
    _422_CODES = {
        RELErrorCode.TAG_NOT_ANNOTATED,
        RELErrorCode.TAG_INCOMPLETE_TREE,
        RELErrorCode.TAG_TREE_CHANGED,
        RELErrorCode.TAG_HOOK_MISSING,
        RELErrorCode.MIGRATION_CHAIN_BROKEN,
        RELErrorCode.DDL_INCOMPLETE,
        RELErrorCode.DDL_MIGRATION_MISMATCH,
        RELErrorCode.OPENAPI_ENDPOINT_MISSING,
        RELErrorCode.RLS_NOT_FORCED,
        RELErrorCode.SEC_CERT_EXPIRED,
        RELErrorCode.PROD_DOSSIER_NOT_SIGNED,
        RELErrorCode.TEST_RESULT_HAS_FAILURE,
        RELErrorCode.PERF_BASELINE_DEGRADED,
        RELErrorCode.IMAGE_FLOATING_TAG,
        RELErrorCode.IMAGE_NOT_LOCKED,
        RELErrorCode.CONFIG_BASELINE_DRIFT,
        RELErrorCode.ROLLBACK_MIGRATION_NOT_INVERSE,
        RELErrorCode.ROLLBACK_DRILL_FAILED,
        RELErrorCode.SEAL_INVALID_STATE_TRANSITION,
        RELErrorCode.UNFREEZE_NOT_APPROVED,
    }
    _423_CODES = {
        RELErrorCode.GATE_MILESTONE_NOT_PASS,
        RELErrorCode.GATE_CORE_TAMPERED,
        RELErrorCode.GATE_REGRESSION_FAILED,
        RELErrorCode.GATE_DIRTY_WORKTREE,
        RELErrorCode.GATE_CERT_INVALID,
        RELErrorCode.ASSET_SNAPSHOT_TAMPERED,
        RELErrorCode.BACKUP_EVIDENCE_TAMPERED,
        RELErrorCode.DR_EVIDENCE_TAMPERED,
        RELErrorCode.SEAL_AUDIT_INVALID,
    }
    _500_CODES = {
        RELErrorCode.PROD_DOSSIER_FAIL,
        RELErrorCode.SEAL_FAIL,
        RELErrorCode.ASSET_SNAPSHOT_COLLECTION_TIMEOUT,
        RELErrorCode.INTERNAL_ERROR,
    }
    _502_CODES = {
        RELErrorCode.TAG_PUSH_FAILED,
        RELErrorCode.DDL_EXPORT_FAILED,
        RELErrorCode.IMAGE_PUSH_FAILED,
        RELErrorCode.CONFIG_EXPORT_FAILED,
        RELErrorCode.ASSET_SNAPSHOT_ARCHIVE_FAILED,
    }
    if code in _403_CODES:
        return 403
    if code in _404_CODES:
        return 404
    if code in _409_CODES:
        return 409
    if code in _422_CODES:
        return 422
    if code in _423_CODES:
        return 423
    if code in _500_CODES:
        return 500
    if code in _502_CODES:
        return 502
    return 400