"""PROD 错误码枚举 - 全部以 EITP_PROD_ 前缀。"""

from __future__ import annotations

from enum import Enum


class PRODErrorCode(str, Enum):
    """EITP PROD 错误码枚举 - 全部以 EITP_PROD_ 前缀。"""

    CORE_FREEZE_VIOLATED = "EITP_PROD_CORE_FREEZE_VIOLATED"
    VERIFICATION_ENV_FORBIDDEN = "EITP_PROD_VERIFICATION_ENV_FORBIDDEN"
    VERIFICATION_NOT_FOUND = "EITP_PROD_VERIFICATION_NOT_FOUND"
    VERIFICATION_ALREADY_RUNNING = "EITP_PROD_VERIFICATION_ALREADY_RUNNING"
    VERIFICATION_PREREQUISITE_NOT_MET = "EITP_PROD_VERIFICATION_PREREQUISITE_NOT_MET"

    BASELINE_INSUFFICIENT_SAMPLES = "EITP_PROD_BASELINE_INSUFFICIENT_SAMPLES"
    BASELINE_LOW_CONFIDENCE = "EITP_PROD_BASELINE_LOW_CONFIDENCE"
    BASELINE_LATENCY_DEGRADED = "EITP_PROD_BASELINE_LATENCY_DEGRADED"

    CONCURRENT_CROSS_TENANT_POLLUTION = "EITP_PROD_CONCURRENT_CROSS_TENANT_POLLUTION"
    CONCURRENT_DATA_INCONSISTENT = "EITP_PROD_CONCURRENT_DATA_INCONSISTENT"
    CONCURRENT_DEADLOCK_DETECTED = "EITP_PROD_CONCURRENT_DEADLOCK_DETECTED"

    CONNPOOL_LEAK_DETECTED = "EITP_PROD_CONNPOOL_LEAK_DETECTED"
    CONNPOOL_EXHAUSTED_NO_TIMEOUT = "EITP_PROD_CONNPOOL_EXHAUSTED_NO_TIMEOUT"

    CACHE_BREAKDOWN_UNPROTECTED = "EITP_PROD_CACHE_BREAKDOWN_UNPROTECTED"
    CACHE_KEY_PREFIX_VIOLATION = "EITP_PROD_CACHE_KEY_PREFIX_VIOLATION"
    CACHE_NO_FALLBACK = "EITP_PROD_CACHE_NO_FALLBACK"

    OUTBOX_EVENT_LOST = "EITP_PROD_OUTBOX_EVENT_LOST"
    OUTBOX_ORDER_VIOLATION = "EITP_PROD_OUTBOX_ORDER_VIOLATION"
    OUTBOX_DEADLETTER_NO_ALERT = "EITP_PROD_OUTBOX_DEADLETTER_NO_ALERT"

    SAGA_COMPENSATION_INCONSISTENT = "EITP_PROD_SAGA_COMPENSATION_INCONSISTENT"
    SAGA_COMPENSATION_NOT_IDEMPOTENT = "EITP_PROD_SAGA_COMPENSATION_NOT_IDEMPOTENT"
    SAGA_COMPENSATION_NO_ALERT = "EITP_PROD_SAGA_COMPENSATION_NO_ALERT"

    JOB_DEFINITION_LOST = "EITP_PROD_JOB_DEFINITION_LOST"
    JOB_MISFIRE_NOT_IDEMPOTENT = "EITP_PROD_JOB_MISFIRE_NOT_IDEMPOTENT"
    JOB_SCHEDULE_DRIFT = "EITP_PROD_JOB_SCHEDULE_DRIFT"

    ALERT_NOT_FIRED = "EITP_PROD_ALERT_NOT_FIRED"
    ALERT_NOTIFICATION_NOT_DELIVERED = "EITP_PROD_ALERT_NOTIFICATION_NOT_DELIVERED"
    ALERT_COVERAGE_GAP = "EITP_PROD_ALERT_COVERAGE_GAP"

    TRACE_BROKEN = "EITP_PROD_TRACE_BROKEN"
    TRACE_ID_INCONSISTENT = "EITP_PROD_TRACE_ID_INCONSISTENT"
    TRACE_EXPLOSION = "EITP_PROD_TRACE_EXPLOSION"

    BACKUP_CORRUPTED = "EITP_PROD_BACKUP_CORRUPTED"
    RESTORE_DATA_MISMATCH = "EITP_PROD_RESTORE_DATA_MISMATCH"
    PITR_PRECISION_INSUFFICIENT = "EITP_PROD_PITR_PRECISION_INSUFFICIENT"
    BACKUP_NOT_ENCRYPTED = "EITP_PROD_BACKUP_NOT_ENCRYPTED"

    DR_DATA_LOSS = "EITP_PROD_DR_DATA_LOSS"
    DR_RTO_EXCEEDED = "EITP_PROD_DR_RTO_EXCEEDED"
    DR_SINGLE_AUTHORIZATION_DENIED = "EITP_PROD_DR_SINGLE_AUTHORIZATION_DENIED"
    DR_API_UNAVAILABLE = "EITP_PROD_DR_API_UNAVAILABLE"

    CONTAINER_RECOVERY_TIMEOUT = "EITP_PROD_CONTAINER_RECOVERY_TIMEOUT"
    INFLIGHT_REQUEST_DROPPED = "EITP_PROD_INFLIGHT_REQUEST_DROPPED"
    DEPENDENCY_ORDER_VIOLATION = "EITP_PROD_DEPENDENCY_ORDER_VIOLATION"

    RATE_LIMIT_NOT_EFFECTIVE = "EITP_PROD_RATE_LIMIT_NOT_EFFECTIVE"
    RATE_LIMIT_CROSS_TENANT = "EITP_PROD_RATE_LIMIT_CROSS_TENANT"
    RATE_LIMIT_FALSE_POSITIVE = "EITP_PROD_RATE_LIMIT_FALSE_POSITIVE"

    LARGE_TENANT_QUERY_SLOW = "EITP_PROD_LARGE_TENANT_QUERY_SLOW"
    LARGE_TENANT_LOW_INDEX_HIT = "EITP_PROD_LARGE_TENANT_LOW_INDEX_HIT"
    LARGE_TENANT_ISOLATION_DEGRADED = "EITP_PROD_LARGE_TENANT_ISOLATION_DEGRADED"

    REGRESSION_BIZ_FAILED = "EITP_PROD_REGRESSION_BIZ_FAILED"
    REGRESSION_SEC_FAILED = "EITP_PROD_REGRESSION_SEC_FAILED"
    REGRESSION_PLT_FAILED = "EITP_PROD_REGRESSION_PLT_FAILED"

    SEC_RECERT_PREREQUISITE_NOT_MET = "EITP_PROD_SEC_RECERT_PREREQUISITE_NOT_MET"
    SEC_RECERT_FAILED = "EITP_PROD_SEC_RECERT_FAILED"
    SEC_RECERT_DEGRADED = "EITP_PROD_SEC_RECERT_DEGRADED"

    DOSSIER_PREREQUISITE_NOT_MET = "EITP_PROD_DOSSIER_PREREQUISITE_NOT_MET"
    DOSSIER_EVIDENCE_MISSING = "EITP_PROD_DOSSIER_EVIDENCE_MISSING"
    DOSSIER_EVIDENCE_TAMPERED = "EITP_PROD_DOSSIER_EVIDENCE_TAMPERED"
    DOSSIER_UNAUTHORIZED_SIGNER = "EITP_PROD_DOSSIER_UNAUTHORIZED_SIGNER"
    DOSSIER_ALREADY_SIGNED = "EITP_PROD_DOSSIER_ALREADY_SIGNED"
    DOSSIER_EXPIRED = "EITP_PROD_DOSSIER_EXPIRED"
    DOSSIER_NOT_FOUND = "EITP_PROD_DOSSIER_NOT_FOUND"

    EVIDENCE_NOT_FOUND = "EITP_PROD_EVIDENCE_NOT_FOUND"
    EVIDENCE_HASH_MISMATCH = "EITP_PROD_EVIDENCE_HASH_MISMATCH"
    INTERNAL_ERROR = "EITP_PROD_INTERNAL_ERROR"
