global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eitp-rel'
    metrics_path: /metrics
    static_configs:
      - targets: ['eitp-backend:8000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'eitp_rel_.*'
        action: keep