version: "3.8"

services:
  locust-master:
    image: locustio/locust:2.32.0
    command: --master -H http://0.0.0.0:8089
    ports:
      - "8089:8089"
    networks:
      - prod-test
    deploy:
      placement:
        constraints: [node.labels.env == staging]

  locust-worker:
    image: locustio/locust:2.32.0
    command: --worker --master-host locust-master
    deploy:
      replicas: 4
      placement:
        constraints: [node.labels.env == staging]
    networks:
      - prod-test
    depends_on:
      - locust-master

networks:
  prod-test:
    driver: overlay
    internal: true