"""REL 错误码枚举 - 全部以 EITP_REL_ 前缀。"""

from __future__ import annotations

from enum import Enum


class RELErrorCode(str, Enum):
    """EITP REL 错误码枚举 - 全部以 EITP_REL_ 前缀。"""

    GATE_MILESTONE_NOT_PASS = "EITP_REL_GATE_MILESTONE_NOT_PASS"
    GATE_CORE_TAMPERED = "EITP_REL_GATE_CORE_TAMPERED"
    GATE_REGRESSION_FAILED = "EITP_REL_GATE_REGRESSION_FAILED"
    GATE_DIRTY_WORKTREE = "EITP_REL_GATE_DIRTY_WORKTREE"
    GATE_TAG_EXISTS = "EITP_REL_GATE_TAG_EXISTS"
    GATE_CERT_INVALID = "EITP_REL_GATE_CERT_INVALID"
    GATE_BYPASS_FORBIDDEN = "EITP_REL_GATE_BYPASS_FORBIDDEN"

    TAG_NOT_ANNOTATED = "EITP_REL_TAG_NOT_ANNOTATED"
    TAG_DELETE_FORBIDDEN = "EITP_REL_TAG_DELETE_FORBIDDEN"
    TAG_MOVE_FORBIDDEN = "EITP_REL_TAG_MOVE_FORBIDDEN"
    TAG_INCOMPLETE_TREE = "EITP_REL_TAG_INCOMPLETE_TREE"
    TAG_TREE_CHANGED = "EITP_REL_TAG_TREE_CHANGED"
    TAG_PUSH_FAILED = "EITP_REL_TAG_PUSH_FAILED"
    TAG_HOOK_MISSING = "EITP_REL_TAG_HOOK_MISSING"

    MIGRATION_CHAIN_BROKEN = "EITP_REL_MIGRATION_CHAIN_BROKEN"
    DDL_INCOMPLETE = "EITP_REL_DDL_INCOMPLETE"
    MIGRATION_FROZEN_MODIFIED = "EITP_REL_MIGRATION_FROZEN_MODIFIED"
    DDL_EXPORT_FAILED = "EITP_REL_DDL_EXPORT_FAILED"
    DDL_MIGRATION_MISMATCH = "EITP_REL_DDL_MIGRATION_MISMATCH"

    OPENAPI_ENDPOINT_MISSING = "EITP_REL_OPENAPI_ENDPOINT_MISSING"
    OPENAPI_CONTRACT_FROZEN_MODIFIED = "EITP_REL_OPENAPI_CONTRACT_FROZEN_MODIFIED"

    PERMISSION_FROZEN_MODIFIED = "EITP_REL_PERMISSION_FROZEN_MODIFIED"
    RLS_FROZEN_MODIFIED = "EITP_REL_RLS_FROZEN_MODIFIED"
    RLS_NOT_FORCED = "EITP_REL_RLS_NOT_FORCED"

    SEC_CERT_EXPIRED = "EITP_REL_SEC_CERT_EXPIRED"
    SEC_CERT_NOT_FOUND = "EITP_REL_SEC_CERT_NOT_FOUND"

    PROD_DOSSIER_FAIL = "EITP_REL_PROD_DOSSIER_FAIL"
    PROD_DOSSIER_NOT_SIGNED = "EITP_REL_PROD_DOSSIER_NOT_SIGNED"

    TEST_RESULT_HAS_FAILURE = "EITP_REL_TEST_RESULT_HAS_FAILURE"
    TEST_RESULT_NOT_FOUND = "EITP_REL_TEST_RESULT_NOT_FOUND"

    PERF_BASELINE_DEGRADED = "EITP_REL_PERF_BASELINE_DEGRADED"
    PERF_BASELINE_NOT_FOUND = "EITP_REL_PERF_BASELINE_NOT_FOUND"

    IMAGE_FLOATING_TAG = "EITP_REL_IMAGE_FLOATING_TAG"
    IMAGE_NOT_LOCKED = "EITP_REL_IMAGE_NOT_LOCKED"
    IMAGE_PUSH_FAILED = "EITP_REL_IMAGE_PUSH_FAILED"

    CONFIG_BASELINE_DRIFT = "EITP_REL_CONFIG_BASELINE_DRIFT"
    CONFIG_EXPORT_FAILED = "EITP_REL_CONFIG_EXPORT_FAILED"

    BACKUP_EVIDENCE_NOT_FOUND = "EITP_REL_BACKUP_EVIDENCE_NOT_FOUND"
    BACKUP_EVIDENCE_TAMPERED = "EITP_REL_BACKUP_EVIDENCE_TAMPERED"

    DR_EVIDENCE_NOT_FOUND = "EITP_REL_DR_EVIDENCE_NOT_FOUND"
    DR_EVIDENCE_TAMPERED = "EITP_REL_DR_EVIDENCE_TAMPERED"

    ROLLBACK_MIGRATION_NOT_INVERSE = "EITP_REL_ROLLBACK_MIGRATION_NOT_INVERSE"
    ROLLBACK_DRILL_FAILED = "EITP_REL_ROLLBACK_DRILL_FAILED"
    ROLLBACK_PLAN_NOT_FOUND = "EITP_REL_ROLLBACK_PLAN_NOT_FOUND"

    FREEZE_DECLARATION_MISSING = "EITP_REL_FREEZE_DECLARATION_MISSING"
    FREEZE_DECLARATION_ALREADY_EFFECTIVE = "EITP_REL_FREEZE_DECLARATION_ALREADY_EFFECTIVE"
    FREEZE_DECLARATION_REVOKED = "EITP_REL_FREEZE_DECLARATION_REVOKED"

    SEAL_NOT_CO_SIGNED = "EITP_REL_SEAL_NOT_CO_SIGNED"
    SEAL_FAIL = "EITP_REL_SEAL_FAIL"
    SEAL_AUDIT_INVALID = "EITP_REL_SEAL_AUDIT_INVALID"
    SEAL_ALREADY_EXISTS = "EITP_REL_SEAL_ALREADY_EXISTS"
    SEAL_NOT_FOUND = "EITP_REL_SEAL_NOT_FOUND"
    SEAL_INVALID_STATE_TRANSITION = "EITP_REL_SEAL_INVALID_STATE_TRANSITION"

    ASSET_SNAPSHOT_TAMPERED = "EITP_REL_ASSET_SNAPSHOT_TAMPERED"
    ASSET_SNAPSHOT_NOT_FOUND = "EITP_REL_ASSET_SNAPSHOT_NOT_FOUND"
    ASSET_SNAPSHOT_COLLECTION_TIMEOUT = "EITP_REL_ASSET_SNAPSHOT_COLLECTION_TIMEOUT"
    ASSET_SNAPSHOT_ARCHIVE_FAILED = "EITP_REL_ASSET_SNAPSHOT_ARCHIVE_FAILED"

    CO_SIGN_UNAUTHORIZED_RELEASER = "EITP_REL_CO_SIGN_UNAUTHORIZED_RELEASER"
    CO_SIGN_UNAUTHORIZED_SECURITY = "EITP_REL_CO_SIGN_UNAUTHORIZED_SECURITY"
    CO_SIGN_ALREADY_SIGNED = "EITP_REL_CO_SIGN_ALREADY_SIGNED"

    UNFREEZE_NOT_APPROVED = "EITP_REL_UNFREEZE_NOT_APPROVED"
    UNFREEZE_FORBIDDEN = "EITP_REL_UNFREEZE_FORBIDDEN"

    INTERNAL_ERROR = "EITP_REL_INTERNAL_ERROR"