"""主数据查询仓储协议（Protocol）。"""

from __future__ import annotations

from typing import Protocol
from uuid import UUID


class MasterDataQueryRepository(Protocol):
    async def query_group_product(self, filter_dict: dict, offset: int = 0, limit: int = 50) -> list[object]: ...
    async def query_enterprise_product(self, tenant_id: UUID, filter_dict: dict, offset: int = 0, limit: int = 50) -> list[object]: ...
    async def locate_by_barcode(self, tenant_id: UUID, barcode: str) -> object | None: ...


class MasterDataAuditRepository(Protocol):
    async def get_by_id(self, audit_id: UUID) -> object | None: ...
    async def list_by_entity(self, entity_type: str, entity_id: str, offset: int = 0, limit: int = 50) -> list[object]: ...
    async def list_by_tenant(self, tenant_id: UUID, offset: int = 0, limit: int = 50) -> list[object]: ...
    async def save(self, aggregate: object) -> object: ...
