"""集团商品目录仓储协议（Protocol）。"""

from __future__ import annotations

from typing import Protocol
from uuid import UUID


class GroupProductRepository(Protocol):
    async def get_by_id(self, group_product_id: UUID) -> object | None: ...
    async def get_by_code(self, code: str) -> object | None: ...
    async def save(self, aggregate: object) -> object: ...
    async def list_all(self, offset: int = 0, limit: int = 50) -> list[object]: ...


class GroupSkuRepository(Protocol):
    async def get_by_id(self, group_sku_id: UUID) -> object | None: ...
    async def get_by_code(self, code: str) -> object | None: ...
    async def save(self, entity: object) -> object: ...


class GroupCategoryRepository(Protocol):
    async def get_by_id(self, group_category_id: UUID) -> object | None: ...
    async def get_by_code(self, code: str) -> object | None: ...
    async def save(self, aggregate: object) -> object: ...
    async def get_tree(self) -> list[object]: ...


class GroupBrandRepository(Protocol):
    async def get_by_id(self, group_brand_id: UUID) -> object | None: ...
    async def save(self, entity: object) -> object: ...


class GroupUnitRepository(Protocol):
    async def get_by_id(self, group_unit_id: UUID) -> object | None: ...
    async def save(self, entity: object) -> object: ...
