"""企业商品仓储协议（Protocol）。"""

from __future__ import annotations

from typing import Protocol
from uuid import UUID


class EnterpriseProductRepository(Protocol):
    async def get_by_id(self, enterprise_product_id: UUID) -> object | None: ...
    async def get_by_tenant_and_code(self, tenant_id: UUID, code: str) -> object | None: ...
    async def save(self, aggregate: object) -> object: ...
    async def list_by_tenant(self, tenant_id: UUID, offset: int = 0, limit: int = 50) -> list[object]: ...


class ProductReferenceRepository(Protocol):
    async def get_by_id(self, reference_id: UUID) -> object | None: ...
    async def save(self, aggregate: object) -> object: ...
    async def list_by_group_product(self, group_product_id: UUID) -> list[object]: ...


class EnterpriseCustomizationRepository(Protocol):
    async def get_by_id(self, customization_id: UUID) -> object | None: ...
    async def save(self, aggregate: object) -> object: ...
