"""治理工作流仓储协议（Protocol）。"""

from __future__ import annotations

from typing import Protocol
from uuid import UUID


class GovernanceRequestRepository(Protocol):
    async def get_by_id(self, request_id: UUID) -> object | None: ...
    async def save(self, aggregate: object) -> object: ...
    async def list_by_tenant(self, tenant_id: UUID, offset: int = 0, limit: int = 50) -> list[object]: ...
    async def list_pending(self, offset: int = 0, limit: int = 50) -> list[object]: ...


class VersionRepository(Protocol):
    async def get_by_id(self, version_id: UUID) -> object | None: ...
    async def list_by_entity(self, entity_type: str, entity_id: str) -> list[object]: ...
    async def save(self, entity: object) -> object: ...
